/* Generated by Amaranth Yosys 0.50 (PyPI ver 0.50.0.0.post129, git sha1 b5170e139) */

(* top =  1  *)
(* generator = "Amaranth" *)
module t2router(eq_rst, eq_data, eq_valid, s_axi_awaddr, s_axi_awvalid, s_axi_wdata, s_axi_wstrb, s_axi_wvalid, s_axi_bready, s_axi_araddr, s_axi_arvalid, s_axi_rready, m_axi_awready, m_axi_wready, m_axi_bid, m_axi_bresp, m_axi_bvalid, m_axi_arready, m_axi_rid, m_axi_rdata, m_axi_rresp
, m_axi_rlast, m_axi_rvalid, clk, rst, s_axi_awready, s_axi_wready, s_axi_bresp, s_axi_bvalid, s_axi_arready, s_axi_rdata, s_axi_rresp, s_axi_rvalid, m_axi_awid, m_axi_awaddr, m_axi_awlen, m_axi_awsize, m_axi_awburst, m_axi_awlock, m_axi_awcache, m_axi_awprot, m_axi_awvalid
, m_axi_wid, m_axi_wdata, m_axi_wstrb, m_axi_wlast, m_axi_wvalid, m_axi_bready, m_axi_arid, m_axi_araddr, m_axi_arlen, m_axi_arsize, m_axi_arburst, m_axi_arlock, m_axi_arcache, m_axi_arprot, m_axi_arvalid, m_axi_rready, eq_clk);
  reg \$auto$verilog_backend.cc:2355:dump_module$1  = 0;
  wire [8:0] \$1 ;
  wire \$10 ;
  reg \$100 ;
  reg [2:0] \$101 ;
  reg [31:0] \$102 ;
  reg [7:0] \$103 ;
  reg \$104 ;
  reg [31:0] \$105 ;
  reg [9:0] \$106 ;
  reg \$107 ;
  reg \$108 ;
  reg [31:0] \$109 ;
  wire \$11 ;
  reg [15:0] \$110 ;
  reg [5:0] \$111 ;
  reg [20:0] \$112 ;
  reg \$113 ;
  reg [1:0] \$114 ;
  reg [7:0] \$115 ;
  reg \$116 ;
  reg \$117 ;
  reg \$118 ;
  reg \$119 ;
  wire \$12 ;
  reg [20:0] \$120 ;
  reg [20:0] \$121 ;
  reg [20:0] \$122 ;
  reg [20:0] \$123 ;
  reg [31:0] \$124 ;
  reg [31:0] \$125 ;
  reg [7:0] \$126 ;
  reg [9:0] \$127 ;
  reg [2:0] \$128 ;
  reg [31:0] \$129 ;
  wire \$13 ;
  reg [63:0] \$130 ;
  reg \$131 ;
  reg [31:0] \$132 ;
  reg \$133 ;
  reg [31:0] \$134 ;
  reg [31:0] \$135 ;
  reg [31:0] \$136 ;
  reg [7:0] \$137 ;
  reg [7:0] \$138 ;
  reg [1:0] \$139 ;
  wire \$14 ;
  reg [31:0] \$140 ;
  wire \$15 ;
  wire \$16 ;
  wire \$17 ;
  wire [8:0] \$18 ;
  wire \$19 ;
  wire [9:0] \$2 ;
  wire [31:0] \$20 ;
  wire [7:0] \$21 ;
  wire [7:0] \$22 ;
  wire [7:0] \$23 ;
  wire [7:0] \$24 ;
  wire \$25 ;
  wire \$26 ;
  wire \$27 ;
  wire [32:0] \$28 ;
  wire \$29 ;
  wire \$3 ;
  wire \$30 ;
  wire \$31 ;
  wire \$32 ;
  wire \$33 ;
  wire \$34 ;
  wire \$35 ;
  wire \$36 ;
  wire \$37 ;
  wire \$38 ;
  wire \$39 ;
  wire \$4 ;
  wire \$40 ;
  wire \$41 ;
  wire \$42 ;
  wire [32:0] \$43 ;
  wire [4:0] \$44 ;
  wire [8:0] \$45 ;
  wire [9:0] \$46 ;
  wire \$47 ;
  wire [32:0] \$48 ;
  wire \$49 ;
  wire \$5 ;
  wire [10:0] \$50 ;
  wire [10:0] \$51 ;
  wire \$52 ;
  wire \$53 ;
  wire [6:0] \$54 ;
  wire [7:0] \$55 ;
  wire \$56 ;
  wire \$57 ;
  wire \$58 ;
  wire \$59 ;
  wire [14:0] \$6 ;
  wire \$60 ;
  wire \$61 ;
  wire \$62 ;
  wire \$63 ;
  wire \$64 ;
  wire \$65 ;
  wire \$66 ;
  wire [2:0] \$67 ;
  wire [2:0] \$68 ;
  wire [2:0] \$69 ;
  wire \$7 ;
  wire [32:0] \$70 ;
  wire [2:0] \$71 ;
  wire [33:0] \$72 ;
  wire [34:0] \$73 ;
  wire [32:0] \$74 ;
  wire \$75 ;
  wire [10:0] \$76 ;
  wire \$77 ;
  wire \$78 ;
  wire \$79 ;
  wire \$8 ;
  wire \$80 ;
  wire \$81 ;
  wire \$82 ;
  wire \$83 ;
  wire \$84 ;
  wire [8:0] \$85 ;
  wire [32:0] \$86 ;
  wire [8:0] \$87 ;
  wire \$88 ;
  wire \$89 ;
  wire \$9 ;
  wire \$90 ;
  wire \$91 ;
  wire \$92 ;
  wire \$93 ;
  wire \$94 ;
  wire \$95 ;
  wire \$96 ;
  reg [20:0] \$97 ;
  reg \$98 ;
  reg \$99 ;
  (* init = 1'h0 *)
  wire ar_pending;
  (* init = 1'h0 *)
  wire aw_pend;
  reg [31:0] base = 32'd0;
  reg [1:0] \buf  = 2'h0;
  reg [20:0] buf_f0 = 21'h000000;
  reg [20:0] buf_f1 = 21'h000000;
  reg [20:0] buf_f2 = 21'h000000;
  reg [20:0] buf_f3 = 21'h000000;
  reg buf_ok0 = 1'h0;
  reg buf_ok1 = 1'h0;
  reg buf_ok2 = 1'h0;
  reg buf_ok3 = 1'h0;
  reg [15:0] \cell ;
  input clk;
  wire clk;
  reg [7:0] count = 8'h00;
  reg [20:0] cur_f = 21'h000000;
  reg [63:0] e = 64'h0000000000000000;
  reg enable = 1'h0;
  reg [31:0] ent;
  input eq_clk;
  wire eq_clk;
  input [31:0] eq_data;
  wire [31:0] eq_data;
  input eq_rst;
  wire eq_rst;
  input eq_valid;
  wire eq_valid;
  reg [31:0] fb = 32'd0;
  reg [2:0] fsm_state = 3'h0;
  reg [1:0] \fsm_state$101  = 2'h0;
  wire got;
  reg half = 1'h0;
  reg have_f = 1'h0;
  reg [5:0] in_flight = 6'h00;
  wire is_last;
  wire issue;
  reg [7:0] j = 8'h00;
  reg [7:0] j0 = 8'h08;
  wire [6:0] level;
  output [31:0] m_axi_araddr;
  reg [31:0] m_axi_araddr = 32'd0;
  output [1:0] m_axi_arburst;
  wire [1:0] m_axi_arburst;
  output [3:0] m_axi_arcache;
  wire [3:0] m_axi_arcache;
  output [5:0] m_axi_arid;
  wire [5:0] m_axi_arid;
  output [3:0] m_axi_arlen;
  wire [3:0] m_axi_arlen;
  output [1:0] m_axi_arlock;
  wire [1:0] m_axi_arlock;
  output [2:0] m_axi_arprot;
  wire [2:0] m_axi_arprot;
  input m_axi_arready;
  wire m_axi_arready;
  output [2:0] m_axi_arsize;
  wire [2:0] m_axi_arsize;
  output m_axi_arvalid;
  reg m_axi_arvalid = 1'h0;
  output [31:0] m_axi_awaddr;
  wire [31:0] m_axi_awaddr;
  output [1:0] m_axi_awburst;
  wire [1:0] m_axi_awburst;
  output [3:0] m_axi_awcache;
  wire [3:0] m_axi_awcache;
  output [5:0] m_axi_awid;
  wire [5:0] m_axi_awid;
  output [3:0] m_axi_awlen;
  wire [3:0] m_axi_awlen;
  output [1:0] m_axi_awlock;
  wire [1:0] m_axi_awlock;
  output [2:0] m_axi_awprot;
  wire [2:0] m_axi_awprot;
  input m_axi_awready;
  wire m_axi_awready;
  output [2:0] m_axi_awsize;
  wire [2:0] m_axi_awsize;
  output m_axi_awvalid;
  reg m_axi_awvalid = 1'h0;
  input [5:0] m_axi_bid;
  wire [5:0] m_axi_bid;
  output m_axi_bready;
  wire m_axi_bready;
  input [1:0] m_axi_bresp;
  wire [1:0] m_axi_bresp;
  input m_axi_bvalid;
  wire m_axi_bvalid;
  input [63:0] m_axi_rdata;
  wire [63:0] m_axi_rdata;
  input [5:0] m_axi_rid;
  wire [5:0] m_axi_rid;
  input m_axi_rlast;
  wire m_axi_rlast;
  output m_axi_rready;
  wire m_axi_rready;
  input [1:0] m_axi_rresp;
  wire [1:0] m_axi_rresp;
  input m_axi_rvalid;
  wire m_axi_rvalid;
  output [63:0] m_axi_wdata;
  wire [63:0] m_axi_wdata;
  output [5:0] m_axi_wid;
  wire [5:0] m_axi_wid;
  output m_axi_wlast;
  wire m_axi_wlast;
  input m_axi_wready;
  wire m_axi_wready;
  output [7:0] m_axi_wstrb;
  wire [7:0] m_axi_wstrb;
  output m_axi_wvalid;
  reg m_axi_wvalid = 1'h0;
  reg [7:0] nsym = 8'hc6;
  reg [7:0] outstanding = 8'h00;
  reg [31:0] overflows = 32'd0;
  reg ovf_eq = 1'h0;
  wire [29:0] payload;
  (* init = 32'd0 *)
  wire [31:0] r_addr;
  wire [31:0] r_data;
  wire [47:0] \r_data$108 ;
  wire [63:0] \r_data$128 ;
  wire r_en;
  reg \r_en$87 ;
  reg \r_en$90 ;
  reg [9:0] r_left = 10'h000;
  wire r_rdy;
  wire \r_rdy$88 ;
  wire \r_rdy$89 ;
  reg [31:0] rd = 32'd0;
  reg ready;
  wire room;
  input rst;
  wire rst;
  input [15:0] s_axi_araddr;
  wire [15:0] s_axi_araddr;
  output s_axi_arready;
  reg s_axi_arready;
  input s_axi_arvalid;
  wire s_axi_arvalid;
  input [15:0] s_axi_awaddr;
  wire [15:0] s_axi_awaddr;
  output s_axi_awready;
  reg s_axi_awready;
  input s_axi_awvalid;
  wire s_axi_awvalid;
  input s_axi_bready;
  wire s_axi_bready;
  output [1:0] s_axi_bresp;
  wire [1:0] s_axi_bresp;
  output s_axi_bvalid;
  reg s_axi_bvalid;
  output [31:0] s_axi_rdata;
  reg [31:0] s_axi_rdata;
  input s_axi_rready;
  wire s_axi_rready;
  output [1:0] s_axi_rresp;
  wire [1:0] s_axi_rresp;
  output s_axi_rvalid;
  reg s_axi_rvalid;
  input [31:0] s_axi_wdata;
  wire [31:0] s_axi_wdata;
  output s_axi_wready;
  reg s_axi_wready;
  input [3:0] s_axi_wstrb;
  wire [3:0] s_axi_wstrb;
  input s_axi_wvalid;
  wire s_axi_wvalid;
  reg [31:0] started = 32'd0;
  reg [31:0] stride = 32'd0;
  reg [31:0] symbols = 32'd0;
  reg [31:0] \table  = 32'd0;
  wire take;
  reg tog_eq = 1'h0;
  reg [2:0] tog_s = 3'h0;
  reg [31:0] w = 32'd0;
  reg [31:0] w_addr = 32'd0;
  reg [15:0] w_cell = 16'h0000;
  wire [31:0] w_data;
  wire [63:0] \w_data$69 ;
  reg [47:0] \w_data$98 ;
  wire w_en;
  reg \w_en$100 ;
  wire \w_en$70 ;
  (* init = 1'h0 *)
  wire w_pend;
  wire w_rdy;
  wire \w_rdy$104 ;
  wire \w_rdy$97 ;
  reg [9:0] widx = 10'h000;
  wire writes_idle;
  assign \$1  = level + outstanding;
  assign \$2  = \$1  + 5'h10;
  assign room = \$2  <= 7'h40;
  assign \$3  = ~ m_axi_arvalid;
  assign \$4  = \$3  & room;
  assign \$5  = | r_left;
  assign issue = \$4  & \$5 ;
  assign got = m_axi_rvalid & m_axi_rready;
  assign \$6  = 2'h3 << w_addr[2:0];
  assign \$7  = ~ m_axi_awvalid;
  assign \$8  = r_rdy & \$7 ;
  assign \$9  = ~ m_axi_wvalid;
  assign \$10  = \$8  & \$9 ;
  assign \$11  = in_flight < 5'h1f;
  assign take = \$10  & \$11 ;
  assign \$12  = ~ r_rdy;
  assign \$13  = ~ m_axi_awvalid;
  assign \$14  = \$12  & \$13 ;
  assign \$15  = ~ m_axi_wvalid;
  assign \$16  = \$14  & \$15 ;
  assign \$17  = ! in_flight;
  assign writes_idle = \$16  & \$17 ;
  assign \$18  = nsym - 1'h1;
  assign is_last = j == \$18 ;
  assign \$19  = \r_rdy$88  & \r_rdy$89 ;
  assign \$20  = half ? e[63:32] : e[31:0];
  assign \$25  = ent == 32'd4294967295;
  assign \$26  = \$25  | \w_rdy$97 ;
  assign \$27  = ent != 32'd4294967295;
  assign \$28  = base + { ent[30:0], 1'h0 };
  assign \$29  = s_axi_awvalid & s_axi_wvalid;
  assign \$30  = ! fsm_state;
  assign \$31  = fsm_state == 1'h1;
  assign \$32  = fsm_state == 2'h2;
  assign \$33  = fsm_state == 2'h3;
  assign \$34  = fsm_state == 3'h4;
  assign \$35  = fsm_state == 3'h5;
  assign \$36  = ! \fsm_state$101 ;
  assign \$37  = \fsm_state$101  == 1'h1;
  assign \$38  = \fsm_state$101  == 2'h2;
  assign \$39  = ~ \w_rdy$104 ;
  assign \$40  = eq_valid & \$39 ;
  assign \$41  = ~ tog_eq;
  assign \$42  = tog_s[1] ^ tog_s[2];
  assign \$43  = overflows + 1'h1;
  assign \$44  = issue ? 5'h10 : 5'h00;
  assign \$45  = outstanding + \$44 ;
  assign \$46  = \$45  - got;
  assign \$47  = m_axi_arvalid & m_axi_arready;
  assign \$48  = m_axi_araddr + 8'h80;
  assign \$49  = r_left > 5'h10;
  assign \$50  = r_left - 5'h10;
  assign \$51  = \$49  ? \$50  : 11'h000;
  assign \$52  = m_axi_awvalid & m_axi_awready;
  assign \$53  = m_axi_wvalid & m_axi_wready;
  assign \$54  = in_flight + take;
  assign \$55  = \$54  - m_axi_bvalid;
  assign \$56  = \r_rdy$88  & r_data[0];
  assign \$57  = \$56  & r_data[16];
  assign \$58  = \$57  & r_data[31];
  assign \$59  = \$58  & enable;
  assign \$60  = r_data[8:1] >= j0;
  assign \$61  = \$59  & \$60 ;
  assign \$62  = r_data[8:1] < nsym;
  assign \$63  = \$61  & \$62 ;
  assign \$64  = ~ have_f;
  assign \$65  = { r_data[30:17], r_data[15:9] } != cur_f;
  assign \$66  = \$64  | \$65 ;
  assign \$67  = \buf  + 1'h1;
  assign \$68  = \buf  + 1'h1;
  assign \$69  = \buf  + 1'h1;
  assign \$70  = started + 1'h1;
  assign \$71  = \buf  + 1'h1;
  assign \$72  = stride * \$71 [1:0];
  assign \$73  = fb + \$72 ;
  assign \$74  = \table  + { r_data[8:1], 13'h0000 };
  assign \$75  = \r_rdy$88  & \r_rdy$89 ;
  assign \$76  = widx + 1'h1;
  assign \$77  = widx == 10'h354;
  assign \$78  = ! r_left;
  assign \$79  = ~ m_axi_arvalid;
  assign \$80  = \$78  & \$79 ;
  assign \$81  = ! outstanding;
  assign \$82  = \$80  & \$81 ;
  assign \$83  = ~ \r_rdy$89 ;
  assign \$84  = \$82  & \$83 ;
  assign \$85  = count + 1'h1;
  assign \$86  = symbols + 1'h1;
  assign \$87  = nsym - j0;
  assign \$88  = count == \$87 ;
  assign \$89  = ! r_left;
  assign \$90  = ~ m_axi_arvalid;
  assign \$91  = \$89  & \$90 ;
  assign \$92  = ! outstanding;
  assign \$93  = \$91  & \$92 ;
  assign \$94  = ~ \r_rdy$89 ;
  assign \$95  = \$93  & \$94 ;
  assign \$96  = s_axi_awvalid & s_axi_wvalid;
  always @(posedge eq_clk)
    ovf_eq <= \$99 ;
  always @(posedge eq_clk)
    tog_eq <= \$100 ;
  always @(posedge clk)
    tog_s <= \$101 ;
  always @(posedge clk)
    overflows <= \$102 ;
  always @(posedge clk)
    outstanding <= \$103 ;
  always @(posedge clk)
    m_axi_arvalid <= \$104 ;
  always @(posedge clk)
    m_axi_araddr <= \$105 ;
  always @(posedge clk)
    r_left <= \$106 ;
  always @(posedge clk)
    m_axi_awvalid <= \$107 ;
  always @(posedge clk)
    m_axi_wvalid <= \$108 ;
  always @(posedge clk)
    w_addr <= \$109 ;
  always @(posedge clk)
    w_cell <= \$110 ;
  always @(posedge clk)
    in_flight <= \$111 ;
  always @(posedge clk)
    cur_f <= \$112 ;
  always @(posedge clk)
    have_f <= \$113 ;
  always @(posedge clk)
    \buf  <= \$114 ;
  always @(posedge clk)
    count <= \$115 ;
  always @(posedge clk)
    buf_ok0 <= \$116 ;
  always @(posedge clk)
    buf_ok1 <= \$117 ;
  always @(posedge clk)
    buf_ok2 <= \$118 ;
  always @(posedge clk)
    buf_ok3 <= \$119 ;
  always @(posedge clk)
    buf_f0 <= \$120 ;
  always @(posedge clk)
    buf_f1 <= \$121 ;
  always @(posedge clk)
    buf_f2 <= \$122 ;
  always @(posedge clk)
    buf_f3 <= \$123 ;
  always @(posedge clk)
    started <= \$124 ;
  always @(posedge clk)
    base <= \$125 ;
  always @(posedge clk)
    j <= \$126 ;
  always @(posedge clk)
    widx <= \$127 ;
  always @(posedge clk)
    fsm_state <= \$128 ;
  always @(posedge clk)
    w <= \$129 ;
  always @(posedge clk)
    e <= \$130 ;
  always @(posedge clk)
    half <= \$131 ;
  always @(posedge clk)
    symbols <= \$132 ;
  always @(posedge clk)
    enable <= \$133 ;
  always @(posedge clk)
    \table  <= \$134 ;
  always @(posedge clk)
    fb <= \$135 ;
  always @(posedge clk)
    stride <= \$136 ;
  always @(posedge clk)
    nsym <= \$137 ;
  always @(posedge clk)
    j0 <= \$138 ;
  always @(posedge clk)
    \fsm_state$101  <= \$139 ;
  always @(posedge clk)
    rd <= \$140 ;
  \t2router.cdc  cdc (
    .clk(clk),
    .eq_clk(eq_clk),
    .eq_rst(eq_rst),
    .r_data(r_data),
    .r_en(\r_en$87 ),
    .r_rdy(\r_rdy$88 ),
    .rst(rst),
    .w_en(eq_valid),
    .w_port__data(eq_data),
    .w_rdy(\w_rdy$104 )
  );
  \t2router.tfifo  tfifo (
    .clk(clk),
    .r_data(\r_data$128 ),
    .r_en(\r_en$90 ),
    .r_rdy(\r_rdy$89 ),
    .rst(rst),
    .w_en(m_axi_rvalid),
    .w_level(level),
    .w_port__data(m_axi_rdata),
    .w_rdy(m_axi_rready)
  );
  \t2router.wfifo  wfifo (
    .clk(clk),
    .r_data(\r_data$108 ),
    .r_en(take),
    .r_rdy(r_rdy),
    .rst(rst),
    .w_en(\w_en$100 ),
    .w_port__data(\w_data$98 ),
    .w_rdy(\w_rdy$97 )
  );
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$1 ) begin end
    (* full_case = 32'd1 *)
    casez (s_axi_araddr[3:2])
      2'h0:
          \$97  = buf_f0;
      2'h1:
          \$97  = buf_f1;
      2'h2:
          \$97  = buf_f2;
      2'h3:
          \$97  = buf_f3;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$1 ) begin end
    (* full_case = 32'd1 *)
    casez (s_axi_araddr[3:2])
      2'h0:
          \$98  = buf_ok0;
      2'h1:
          \$98  = buf_ok1;
      2'h2:
          \$98  = buf_ok2;
      2'h3:
          \$98  = buf_ok3;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$1 ) begin end
    \r_en$87  = 1'h0;
    casez (fsm_state)
      3'h0:
          \r_en$87  = \r_rdy$88 ;
      3'h1:
          if (\$19 ) begin
            (* full_case = 32'd1 *)
            if (r_data[0]) begin
            end else begin
              \r_en$87  = 1'h1;
            end
          end
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$1 ) begin end
    \r_en$90  = 1'h0;
    casez (fsm_state)
      3'h0:
          /* empty */;
      3'h1:
          if (\$19 ) begin
            (* full_case = 32'd1 *)
            if (r_data[0]) begin
            end else begin
              \r_en$90  = 1'h1;
            end
          end
      3'h3:
          /* empty */;
      3'h4:
          \r_en$90  = \r_rdy$89 ;
      3'h5:
          /* empty */;
      3'h2:
          \r_en$90  = \r_rdy$89 ;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$1 ) begin end
    ent = 32'd0;
    casez (fsm_state)
      3'h0:
          /* empty */;
      3'h1:
          /* empty */;
      3'h3:
          ent = \$20 ;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$1 ) begin end
    \cell  = 16'h0000;
    casez (fsm_state)
      3'h0:
          /* empty */;
      3'h1:
          /* empty */;
      3'h3:
          (* full_case = 32'd1 *)
          if (half) begin
            \cell  = { \$22 , \$21  };
          end else begin
            \cell  = { \$24 , \$23  };
          end
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$1 ) begin end
    ready = 1'h0;
    casez (fsm_state)
      3'h0:
          /* empty */;
      3'h1:
          /* empty */;
      3'h3:
          ready = \$26 ;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$1 ) begin end
    \w_data$98  = 48'h000000000000;
    casez (fsm_state)
      3'h0:
          /* empty */;
      3'h1:
          /* empty */;
      3'h3:
          if (ready) begin
            if (\$27 ) begin
              \w_data$98  = { \cell , \$28 [31:0] };
            end
          end
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$1 ) begin end
    \w_en$100  = 1'h0;
    casez (fsm_state)
      3'h0:
          /* empty */;
      3'h1:
          /* empty */;
      3'h3:
          if (ready) begin
            if (\$27 ) begin
              \w_en$100  = 1'h1;
            end
          end
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$1 ) begin end
    s_axi_awready = 1'h0;
    casez (\fsm_state$101 )
      2'h0:
          if (\$29 ) begin
            s_axi_awready = 1'h1;
          end
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$1 ) begin end
    s_axi_wready = 1'h0;
    casez (\fsm_state$101 )
      2'h0:
          if (\$29 ) begin
            s_axi_wready = 1'h1;
          end
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$1 ) begin end
    s_axi_arready = 1'h0;
    casez (\fsm_state$101 )
      2'h0:
          if (\$29 ) begin
          end else if (s_axi_arvalid) begin
            s_axi_arready = 1'h1;
          end
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$1 ) begin end
    s_axi_bvalid = 1'h0;
    casez (\fsm_state$101 )
      2'h0:
          /* empty */;
      2'h1:
          s_axi_bvalid = 1'h1;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$1 ) begin end
    s_axi_rvalid = 1'h0;
    casez (\fsm_state$101 )
      2'h0:
          /* empty */;
      2'h1:
          /* empty */;
      2'h2:
          s_axi_rvalid = 1'h1;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$1 ) begin end
    s_axi_rdata = 32'd0;
    casez (\fsm_state$101 )
      2'h0:
          /* empty */;
      2'h1:
          /* empty */;
      2'h2:
          s_axi_rdata = rd;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$1 ) begin end
    \$99  = \$40 ;
    if (eq_rst) begin
      \$99  = 1'h0;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$1 ) begin end
    \$100  = tog_eq;
    if (ovf_eq) begin
      \$100  = \$41 ;
    end
    if (eq_rst) begin
      \$100  = 1'h0;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$1 ) begin end
    \$101  = { tog_s[1:0], tog_eq };
    if (rst) begin
      \$101  = 3'h0;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$1 ) begin end
    \$102  = overflows;
    if (\$42 ) begin
      \$102  = \$43 [31:0];
    end
    if (rst) begin
      \$102  = 32'd0;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$1 ) begin end
    \$103  = \$46 [7:0];
    if (rst) begin
      \$103  = 8'h00;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$1 ) begin end
    \$104  = m_axi_arvalid;
    if (issue) begin
      \$104  = 1'h1;
    end
    if (\$47 ) begin
      \$104  = 1'h0;
    end
    if (rst) begin
      \$104  = 1'h0;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$1 ) begin end
    \$105  = m_axi_araddr;
    if (\$47 ) begin
      \$105  = \$48 [31:0];
    end
    casez (fsm_state)
      3'h0:
          if (\$63 ) begin
            \$105  = \$74 [31:0];
          end
    endcase
    if (rst) begin
      \$105  = 32'd0;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$1 ) begin end
    \$106  = r_left;
    if (\$47 ) begin
      \$106  = \$51 [9:0];
    end
    casez (fsm_state)
      3'h0:
          if (\$63 ) begin
            \$106  = 10'h360;
          end
    endcase
    if (rst) begin
      \$106  = 10'h000;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$1 ) begin end
    \$107  = m_axi_awvalid;
    if (take) begin
      \$107  = 1'h1;
    end
    if (\$52 ) begin
      \$107  = 1'h0;
    end
    if (rst) begin
      \$107  = 1'h0;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$1 ) begin end
    \$108  = m_axi_wvalid;
    if (take) begin
      \$108  = 1'h1;
    end
    if (\$53 ) begin
      \$108  = 1'h0;
    end
    if (rst) begin
      \$108  = 1'h0;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$1 ) begin end
    \$109  = w_addr;
    if (take) begin
      \$109  = \r_data$108 [31:0];
    end
    if (rst) begin
      \$109  = 32'd0;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$1 ) begin end
    \$110  = w_cell;
    if (take) begin
      \$110  = \r_data$108 [47:32];
    end
    if (rst) begin
      \$110  = 16'h0000;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$1 ) begin end
    \$111  = \$55 [5:0];
    if (rst) begin
      \$111  = 6'h00;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$1 ) begin end
    \$112  = cur_f;
    casez (fsm_state)
      3'h0:
          if (\$63 ) begin
            if (\$66 ) begin
              \$112  = { r_data[30:17], r_data[15:9] };
            end
          end
    endcase
    if (rst) begin
      \$112  = 21'h000000;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$1 ) begin end
    \$113  = have_f;
    casez (fsm_state)
      3'h0:
          if (\$63 ) begin
            if (\$66 ) begin
              \$113  = 1'h1;
            end
          end
    endcase
    if (rst) begin
      \$113  = 1'h0;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$1 ) begin end
    \$114  = \buf ;
    casez (fsm_state)
      3'h0:
          if (\$63 ) begin
            if (\$66 ) begin
              \$114  = \$67 [1:0];
            end
          end
    endcase
    if (rst) begin
      \$114  = 2'h0;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$1 ) begin end
    \$115  = count;
    casez (fsm_state)
      3'h0:
          if (\$63 ) begin
            if (\$66 ) begin
              \$115  = 8'h00;
            end
          end
      3'h1:
          /* empty */;
      3'h3:
          /* empty */;
      3'h4:
          if (\$84 ) begin
            \$115  = \$85 [7:0];
          end
    endcase
    if (rst) begin
      \$115  = 8'h00;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$1 ) begin end
    \$116  = buf_ok0;
    casez (fsm_state)
      3'h0:
          if (\$63 ) begin
            if (\$66 ) begin
              casez (\$68 [1:0])
                2'h0:
                    \$116  = 1'h0;
              endcase
            end
          end
      3'h1:
          /* empty */;
      3'h3:
          /* empty */;
      3'h4:
          /* empty */;
      3'h5:
          if (writes_idle) begin
            if (\$88 ) begin
              casez (\buf )
                2'h0:
                    \$116  = 1'h1;
              endcase
            end
          end
    endcase
    if (rst) begin
      \$116  = 1'h0;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$1 ) begin end
    \$117  = buf_ok1;
    casez (fsm_state)
      3'h0:
          if (\$63 ) begin
            if (\$66 ) begin
              casez (\$68 [1:0])
                2'h0:
                    /* empty */;
                2'h1:
                    \$117  = 1'h0;
              endcase
            end
          end
      3'h1:
          /* empty */;
      3'h3:
          /* empty */;
      3'h4:
          /* empty */;
      3'h5:
          if (writes_idle) begin
            if (\$88 ) begin
              casez (\buf )
                2'h0:
                    /* empty */;
                2'h1:
                    \$117  = 1'h1;
              endcase
            end
          end
    endcase
    if (rst) begin
      \$117  = 1'h0;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$1 ) begin end
    \$118  = buf_ok2;
    casez (fsm_state)
      3'h0:
          if (\$63 ) begin
            if (\$66 ) begin
              casez (\$68 [1:0])
                2'h0:
                    /* empty */;
                2'h1:
                    /* empty */;
                2'h2:
                    \$118  = 1'h0;
              endcase
            end
          end
      3'h1:
          /* empty */;
      3'h3:
          /* empty */;
      3'h4:
          /* empty */;
      3'h5:
          if (writes_idle) begin
            if (\$88 ) begin
              casez (\buf )
                2'h0:
                    /* empty */;
                2'h1:
                    /* empty */;
                2'h2:
                    \$118  = 1'h1;
              endcase
            end
          end
    endcase
    if (rst) begin
      \$118  = 1'h0;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$1 ) begin end
    \$119  = buf_ok3;
    casez (fsm_state)
      3'h0:
          if (\$63 ) begin
            if (\$66 ) begin
              (* full_case = 32'd1 *)
              casez (\$68 [1:0])
                2'h0:
                    /* empty */;
                2'h1:
                    /* empty */;
                2'h2:
                    /* empty */;
                2'h3:
                    \$119  = 1'h0;
              endcase
            end
          end
      3'h1:
          /* empty */;
      3'h3:
          /* empty */;
      3'h4:
          /* empty */;
      3'h5:
          if (writes_idle) begin
            if (\$88 ) begin
              (* full_case = 32'd1 *)
              casez (\buf )
                2'h0:
                    /* empty */;
                2'h1:
                    /* empty */;
                2'h2:
                    /* empty */;
                2'h3:
                    \$119  = 1'h1;
              endcase
            end
          end
    endcase
    if (rst) begin
      \$119  = 1'h0;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$1 ) begin end
    \$120  = buf_f0;
    casez (fsm_state)
      3'h0:
          if (\$63 ) begin
            if (\$66 ) begin
              casez (\$69 [1:0])
                2'h0:
                    \$120  = { r_data[30:17], r_data[15:9] };
              endcase
            end
          end
    endcase
    if (rst) begin
      \$120  = 21'h000000;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$1 ) begin end
    \$121  = buf_f1;
    casez (fsm_state)
      3'h0:
          if (\$63 ) begin
            if (\$66 ) begin
              casez (\$69 [1:0])
                2'h0:
                    /* empty */;
                2'h1:
                    \$121  = { r_data[30:17], r_data[15:9] };
              endcase
            end
          end
    endcase
    if (rst) begin
      \$121  = 21'h000000;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$1 ) begin end
    \$122  = buf_f2;
    casez (fsm_state)
      3'h0:
          if (\$63 ) begin
            if (\$66 ) begin
              casez (\$69 [1:0])
                2'h0:
                    /* empty */;
                2'h1:
                    /* empty */;
                2'h2:
                    \$122  = { r_data[30:17], r_data[15:9] };
              endcase
            end
          end
    endcase
    if (rst) begin
      \$122  = 21'h000000;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$1 ) begin end
    \$123  = buf_f3;
    casez (fsm_state)
      3'h0:
          if (\$63 ) begin
            if (\$66 ) begin
              (* full_case = 32'd1 *)
              casez (\$69 [1:0])
                2'h0:
                    /* empty */;
                2'h1:
                    /* empty */;
                2'h2:
                    /* empty */;
                2'h3:
                    \$123  = { r_data[30:17], r_data[15:9] };
              endcase
            end
          end
    endcase
    if (rst) begin
      \$123  = 21'h000000;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$1 ) begin end
    \$124  = started;
    casez (fsm_state)
      3'h0:
          if (\$63 ) begin
            if (\$66 ) begin
              \$124  = \$70 [31:0];
            end
          end
    endcase
    if (rst) begin
      \$124  = 32'd0;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$1 ) begin end
    \$125  = base;
    casez (fsm_state)
      3'h0:
          if (\$63 ) begin
            if (\$66 ) begin
              \$125  = \$73 [31:0];
            end
          end
    endcase
    if (rst) begin
      \$125  = 32'd0;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$1 ) begin end
    \$126  = j;
    casez (fsm_state)
      3'h0:
          if (\$63 ) begin
            \$126  = r_data[8:1];
          end
    endcase
    if (rst) begin
      \$126  = 8'h00;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$1 ) begin end
    \$127  = widx;
    casez (fsm_state)
      3'h0:
          if (\$63 ) begin
            \$127  = 10'h000;
          end
      3'h1:
          /* empty */;
      3'h3:
          if (ready) begin
            if (half) begin
              \$127  = \$76 [9:0];
            end
          end
    endcase
    if (rst) begin
      \$127  = 10'h000;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$1 ) begin end
    \$128  = fsm_state;
    casez (fsm_state)
      3'h0:
          if (\$63 ) begin
            \$128  = 3'h1;
          end
      3'h1:
          if (\$75 ) begin
            (* full_case = 32'd1 *)
            if (r_data[0]) begin
              \$128  = 3'h2;
            end else begin
              \$128  = 3'h3;
            end
          end
      3'h3:
          if (ready) begin
            if (half) begin
              (* full_case = 32'd1 *)
              if (\$77 ) begin
                \$128  = 3'h4;
              end else begin
                \$128  = 3'h1;
              end
            end
          end
      3'h4:
          if (\$84 ) begin
            (* full_case = 32'd1 *)
            if (is_last) begin
              \$128  = 3'h5;
            end else begin
              \$128  = 3'h0;
            end
          end
      3'h5:
          if (writes_idle) begin
            \$128  = 3'h0;
          end
      3'h2:
          if (\$95 ) begin
            \$128  = 3'h0;
          end
    endcase
    if (rst) begin
      \$128  = 3'h0;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$1 ) begin end
    \$129  = w;
    casez (fsm_state)
      3'h0:
          /* empty */;
      3'h1:
          if (\$75 ) begin
            (* full_case = 32'd1 *)
            if (r_data[0]) begin
            end else begin
              \$129  = r_data;
            end
          end
    endcase
    if (rst) begin
      \$129  = 32'd0;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$1 ) begin end
    \$130  = e;
    casez (fsm_state)
      3'h0:
          /* empty */;
      3'h1:
          if (\$75 ) begin
            (* full_case = 32'd1 *)
            if (r_data[0]) begin
            end else begin
              \$130  = \r_data$128 ;
            end
          end
    endcase
    if (rst) begin
      \$130  = 64'h0000000000000000;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$1 ) begin end
    \$131  = half;
    casez (fsm_state)
      3'h0:
          /* empty */;
      3'h1:
          if (\$75 ) begin
            (* full_case = 32'd1 *)
            if (r_data[0]) begin
            end else begin
              \$131  = 1'h0;
            end
          end
      3'h3:
          if (ready) begin
            \$131  = 1'h1;
          end
    endcase
    if (rst) begin
      \$131  = 1'h0;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$1 ) begin end
    \$132  = symbols;
    casez (fsm_state)
      3'h0:
          /* empty */;
      3'h1:
          /* empty */;
      3'h3:
          /* empty */;
      3'h4:
          if (\$84 ) begin
            \$132  = \$86 [31:0];
          end
    endcase
    if (rst) begin
      \$132  = 32'd0;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$1 ) begin end
    \$133  = enable;
    casez (\fsm_state$101 )
      2'h0:
          if (\$96 ) begin
            casez (s_axi_awaddr[7:0])
              8'h00:
                  \$133  = s_axi_wdata[0];
            endcase
          end
    endcase
    if (rst) begin
      \$133  = 1'h0;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$1 ) begin end
    \$134  = \table ;
    casez (\fsm_state$101 )
      2'h0:
          if (\$96 ) begin
            casez (s_axi_awaddr[7:0])
              8'h00:
                  /* empty */;
              8'h04:
                  \$134  = s_axi_wdata;
            endcase
          end
    endcase
    if (rst) begin
      \$134  = 32'd0;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$1 ) begin end
    \$135  = fb;
    casez (\fsm_state$101 )
      2'h0:
          if (\$96 ) begin
            casez (s_axi_awaddr[7:0])
              8'h00:
                  /* empty */;
              8'h04:
                  /* empty */;
              8'h08:
                  \$135  = s_axi_wdata;
            endcase
          end
    endcase
    if (rst) begin
      \$135  = 32'd0;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$1 ) begin end
    \$136  = stride;
    casez (\fsm_state$101 )
      2'h0:
          if (\$96 ) begin
            casez (s_axi_awaddr[7:0])
              8'h00:
                  /* empty */;
              8'h04:
                  /* empty */;
              8'h08:
                  /* empty */;
              8'h0c:
                  \$136  = s_axi_wdata;
            endcase
          end
    endcase
    if (rst) begin
      \$136  = 32'd0;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$1 ) begin end
    \$137  = nsym;
    casez (\fsm_state$101 )
      2'h0:
          if (\$96 ) begin
            casez (s_axi_awaddr[7:0])
              8'h00:
                  /* empty */;
              8'h04:
                  /* empty */;
              8'h08:
                  /* empty */;
              8'h0c:
                  /* empty */;
              8'h10:
                  \$137  = s_axi_wdata[7:0];
            endcase
          end
    endcase
    if (rst) begin
      \$137  = 8'hc6;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$1 ) begin end
    \$138  = j0;
    casez (\fsm_state$101 )
      2'h0:
          if (\$96 ) begin
            casez (s_axi_awaddr[7:0])
              8'h00:
                  /* empty */;
              8'h04:
                  /* empty */;
              8'h08:
                  /* empty */;
              8'h0c:
                  /* empty */;
              8'h10:
                  /* empty */;
              8'h14:
                  \$138  = s_axi_wdata[7:0];
            endcase
          end
    endcase
    if (rst) begin
      \$138  = 8'h08;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$1 ) begin end
    \$139  = \fsm_state$101 ;
    casez (\fsm_state$101 )
      2'h0:
          if (\$96 ) begin
            \$139  = 2'h1;
          end else if (s_axi_arvalid) begin
            \$139  = 2'h2;
          end
      2'h1:
          if (s_axi_bready) begin
            \$139  = 2'h0;
          end
      2'h2:
          if (s_axi_rready) begin
            \$139  = 2'h0;
          end
    endcase
    if (rst) begin
      \$139  = 2'h0;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$1 ) begin end
    \$140  = rd;
    casez (\fsm_state$101 )
      2'h0:
          if (\$96 ) begin
          end else if (s_axi_arvalid) begin
            (* full_case = 32'd1 *)
            casez (s_axi_araddr[7:0])
              8'h00:
                  \$140  = { 31'h00000000, enable };
              8'h04:
                  \$140  = \table ;
              8'h08:
                  \$140  = fb;
              8'h0c:
                  \$140  = stride;
              8'h10:
                  \$140  = { 24'h000000, nsym };
              8'h14:
                  \$140  = { 24'h000000, j0 };
              8'h20, 8'h24, 8'h28, 8'h2c:
                  \$140  = { \$98 , 10'h000, \$97  };
              8'h30:
                  \$140  = started;
              8'h34:
                  \$140  = symbols;
              8'h38:
                  \$140  = overflows;
              8'h3c:
                  \$140  = 32'd827470420;
              default:
                  \$140  = 32'd0;
            endcase
          end
    endcase
    if (rst) begin
      \$140  = 32'd0;
    end
  end
  assign w_data = eq_data;
  assign w_en = eq_valid;
  assign ar_pending = m_axi_arvalid;
  assign r_addr = m_axi_araddr;
  assign w_rdy = m_axi_rready;
  assign \w_data$69  = m_axi_rdata;
  assign \w_en$70  = m_axi_rvalid;
  assign aw_pend = m_axi_awvalid;
  assign w_pend = m_axi_wvalid;
  assign r_en = take;
  assign payload = { r_data[31:17], r_data[15:1] };
  assign s_axi_bresp = 2'h0;
  assign s_axi_rresp = 2'h0;
  assign m_axi_awid = 6'h00;
  assign m_axi_awaddr = { w_addr[31:3], 3'h0 };
  assign m_axi_awlen = 4'h0;
  assign m_axi_awsize = 3'h3;
  assign m_axi_awburst = 2'h1;
  assign m_axi_awlock = 2'h0;
  assign m_axi_awcache = 4'h3;
  assign m_axi_awprot = 3'h0;
  assign m_axi_wid = 6'h00;
  assign m_axi_wdata = { w_cell, w_cell, w_cell, w_cell };
  assign m_axi_wstrb = \$6 [7:0];
  assign m_axi_wlast = 1'h1;
  assign m_axi_bready = 1'h1;
  assign m_axi_arid = 6'h00;
  assign m_axi_arlen = 4'hf;
  assign m_axi_arsize = 3'h3;
  assign m_axi_arburst = 2'h1;
  assign m_axi_arlock = 2'h0;
  assign m_axi_arcache = 4'h3;
  assign m_axi_arprot = 3'h0;
  assign \$21 [0] = 1'h0;
  assign \$21 [7:1] = w[23:17];
  assign \$22  = { w[30:24], 1'h0 };
  assign \$23 [0] = 1'h0;
  assign \$23 [7:1] = w[7:1];
  assign \$24  = { w[14:8], 1'h0 };
endmodule

(* generator = "Amaranth" *)
module \t2router.cdc (eq_rst, w_port__data, w_en, clk, rst, w_rdy, r_rdy, r_data, r_en, eq_clk);
  reg \$auto$verilog_backend.cc:2355:dump_module$2  = 0;
  wire \$1 ;
  wire \$10 ;
  wire \$100 ;
  wire \$101 ;
  wire \$102 ;
  wire \$103 ;
  wire \$104 ;
  wire \$105 ;
  wire \$106 ;
  wire \$107 ;
  wire \$108 ;
  wire \$109 ;
  wire \$11 ;
  wire \$110 ;
  wire \$111 ;
  wire \$112 ;
  wire \$113 ;
  wire \$114 ;
  wire \$115 ;
  wire \$116 ;
  wire \$117 ;
  wire \$118 ;
  wire \$119 ;
  wire \$12 ;
  wire \$120 ;
  wire \$121 ;
  wire \$122 ;
  wire \$123 ;
  wire \$124 ;
  wire \$125 ;
  wire \$126 ;
  wire \$127 ;
  wire \$128 ;
  wire \$129 ;
  wire \$13 ;
  wire \$130 ;
  wire \$131 ;
  wire \$132 ;
  wire \$133 ;
  wire \$134 ;
  wire \$135 ;
  wire \$136 ;
  wire \$137 ;
  wire \$138 ;
  wire \$139 ;
  wire \$14 ;
  wire \$140 ;
  wire \$141 ;
  wire \$142 ;
  wire \$143 ;
  wire [11:0] \$144 ;
  wire [10:0] \$145 ;
  wire \$146 ;
  wire \$147 ;
  wire \$148 ;
  wire \$149 ;
  wire \$15 ;
  wire \$150 ;
  wire \$151 ;
  wire \$152 ;
  wire \$153 ;
  wire \$154 ;
  wire \$155 ;
  wire \$156 ;
  wire \$157 ;
  wire \$158 ;
  wire \$159 ;
  wire \$16 ;
  wire \$160 ;
  wire \$161 ;
  wire \$162 ;
  wire \$163 ;
  wire \$164 ;
  wire \$165 ;
  wire \$166 ;
  wire \$167 ;
  wire \$168 ;
  wire \$169 ;
  wire \$17 ;
  wire \$170 ;
  wire \$171 ;
  wire \$172 ;
  wire \$173 ;
  wire \$174 ;
  wire \$175 ;
  wire \$176 ;
  wire \$177 ;
  wire \$178 ;
  wire \$179 ;
  wire \$18 ;
  wire \$180 ;
  wire \$181 ;
  wire \$182 ;
  wire \$183 ;
  wire \$184 ;
  wire \$185 ;
  wire \$186 ;
  wire \$187 ;
  wire \$188 ;
  wire \$189 ;
  wire \$19 ;
  wire \$190 ;
  wire \$191 ;
  wire \$192 ;
  wire \$193 ;
  wire \$194 ;
  wire \$195 ;
  wire \$196 ;
  wire \$197 ;
  wire \$198 ;
  wire \$199 ;
  wire [11:0] \$2 ;
  wire \$20 ;
  wire \$200 ;
  wire \$201 ;
  wire \$202 ;
  wire \$203 ;
  wire \$204 ;
  wire \$205 ;
  wire \$206 ;
  wire \$207 ;
  wire \$208 ;
  wire \$209 ;
  wire \$21 ;
  wire \$210 ;
  wire \$211 ;
  reg [10:0] \$212 ;
  reg [10:0] \$213 ;
  reg [10:0] \$214 ;
  reg [10:0] \$215 ;
  reg [10:0] \$216 ;
  reg [10:0] \$217 ;
  reg \$218 ;
  wire \$22 ;
  wire \$23 ;
  wire \$24 ;
  wire \$25 ;
  wire \$26 ;
  wire \$27 ;
  wire \$28 ;
  wire \$29 ;
  wire \$3 ;
  wire \$30 ;
  wire \$31 ;
  wire \$32 ;
  wire \$33 ;
  wire \$34 ;
  wire \$35 ;
  wire \$36 ;
  wire \$37 ;
  wire \$38 ;
  wire \$39 ;
  wire [11:0] \$4 ;
  wire \$40 ;
  wire \$41 ;
  wire \$42 ;
  wire \$43 ;
  wire \$44 ;
  wire \$45 ;
  wire \$46 ;
  wire \$47 ;
  wire \$48 ;
  wire \$49 ;
  wire \$5 ;
  wire \$50 ;
  wire \$51 ;
  wire \$52 ;
  wire \$53 ;
  wire \$54 ;
  wire \$55 ;
  wire \$56 ;
  wire \$57 ;
  wire \$58 ;
  wire \$59 ;
  wire \$6 ;
  wire \$60 ;
  wire \$61 ;
  wire \$62 ;
  wire \$63 ;
  wire \$64 ;
  wire \$65 ;
  wire \$66 ;
  wire \$67 ;
  wire \$68 ;
  wire \$69 ;
  wire \$7 ;
  wire \$70 ;
  wire \$71 ;
  wire \$72 ;
  wire \$73 ;
  wire \$74 ;
  wire \$75 ;
  wire [11:0] \$76 ;
  wire [10:0] \$77 ;
  wire \$78 ;
  wire \$79 ;
  wire \$8 ;
  wire \$80 ;
  wire \$81 ;
  wire \$82 ;
  wire \$83 ;
  wire \$84 ;
  wire \$85 ;
  wire \$86 ;
  wire \$87 ;
  wire \$88 ;
  wire \$89 ;
  wire \$9 ;
  wire \$90 ;
  wire \$91 ;
  wire \$92 ;
  wire \$93 ;
  wire \$94 ;
  wire \$95 ;
  wire \$96 ;
  wire \$97 ;
  wire \$98 ;
  wire \$99 ;
  input clk;
  wire clk;
  reg [10:0] consume_r_bin = 11'h000;
  reg [10:0] consume_r_gry = 11'h000;
  wire [10:0] consume_r_nxt;
  reg [10:0] consume_w_bin = 11'h000;
  wire [10:0] consume_w_gry;
  input eq_clk;
  wire eq_clk;
  input eq_rst;
  wire eq_rst;
  wire [10:0] produce_r_bin;
  wire [10:0] produce_r_gry;
  reg [10:0] produce_w_bin = 11'h000;
  reg [10:0] produce_w_gry = 11'h000;
  wire [10:0] produce_w_nxt;
  output [31:0] r_data;
  wire [31:0] r_data;
  reg r_empty;
  input r_en;
  wire r_en;
  wire [10:0] r_level;
  wire [9:0] r_port__addr;
  wire [31:0] r_port__data;
  wire r_port__en;
  output r_rdy;
  wire r_rdy;
  wire r_rst;
  reg \r_rst$31  = 1'h0;
  input rst;
  wire rst;
  wire [31:0] w_data;
  input w_en;
  wire w_en;
  wire w_full;
  reg [10:0] w_level = 11'h000;
  wire [9:0] w_port__addr;
  input [31:0] w_port__data;
  wire [31:0] w_port__data;
  wire w_port__en;
  output w_rdy;
  wire w_rdy;
  reg [31:0] storage [1023:0];
  initial begin
    storage[0] = 32'd0;
    storage[1] = 32'd0;
    storage[2] = 32'd0;
    storage[3] = 32'd0;
    storage[4] = 32'd0;
    storage[5] = 32'd0;
    storage[6] = 32'd0;
    storage[7] = 32'd0;
    storage[8] = 32'd0;
    storage[9] = 32'd0;
    storage[10] = 32'd0;
    storage[11] = 32'd0;
    storage[12] = 32'd0;
    storage[13] = 32'd0;
    storage[14] = 32'd0;
    storage[15] = 32'd0;
    storage[16] = 32'd0;
    storage[17] = 32'd0;
    storage[18] = 32'd0;
    storage[19] = 32'd0;
    storage[20] = 32'd0;
    storage[21] = 32'd0;
    storage[22] = 32'd0;
    storage[23] = 32'd0;
    storage[24] = 32'd0;
    storage[25] = 32'd0;
    storage[26] = 32'd0;
    storage[27] = 32'd0;
    storage[28] = 32'd0;
    storage[29] = 32'd0;
    storage[30] = 32'd0;
    storage[31] = 32'd0;
    storage[32] = 32'd0;
    storage[33] = 32'd0;
    storage[34] = 32'd0;
    storage[35] = 32'd0;
    storage[36] = 32'd0;
    storage[37] = 32'd0;
    storage[38] = 32'd0;
    storage[39] = 32'd0;
    storage[40] = 32'd0;
    storage[41] = 32'd0;
    storage[42] = 32'd0;
    storage[43] = 32'd0;
    storage[44] = 32'd0;
    storage[45] = 32'd0;
    storage[46] = 32'd0;
    storage[47] = 32'd0;
    storage[48] = 32'd0;
    storage[49] = 32'd0;
    storage[50] = 32'd0;
    storage[51] = 32'd0;
    storage[52] = 32'd0;
    storage[53] = 32'd0;
    storage[54] = 32'd0;
    storage[55] = 32'd0;
    storage[56] = 32'd0;
    storage[57] = 32'd0;
    storage[58] = 32'd0;
    storage[59] = 32'd0;
    storage[60] = 32'd0;
    storage[61] = 32'd0;
    storage[62] = 32'd0;
    storage[63] = 32'd0;
    storage[64] = 32'd0;
    storage[65] = 32'd0;
    storage[66] = 32'd0;
    storage[67] = 32'd0;
    storage[68] = 32'd0;
    storage[69] = 32'd0;
    storage[70] = 32'd0;
    storage[71] = 32'd0;
    storage[72] = 32'd0;
    storage[73] = 32'd0;
    storage[74] = 32'd0;
    storage[75] = 32'd0;
    storage[76] = 32'd0;
    storage[77] = 32'd0;
    storage[78] = 32'd0;
    storage[79] = 32'd0;
    storage[80] = 32'd0;
    storage[81] = 32'd0;
    storage[82] = 32'd0;
    storage[83] = 32'd0;
    storage[84] = 32'd0;
    storage[85] = 32'd0;
    storage[86] = 32'd0;
    storage[87] = 32'd0;
    storage[88] = 32'd0;
    storage[89] = 32'd0;
    storage[90] = 32'd0;
    storage[91] = 32'd0;
    storage[92] = 32'd0;
    storage[93] = 32'd0;
    storage[94] = 32'd0;
    storage[95] = 32'd0;
    storage[96] = 32'd0;
    storage[97] = 32'd0;
    storage[98] = 32'd0;
    storage[99] = 32'd0;
    storage[100] = 32'd0;
    storage[101] = 32'd0;
    storage[102] = 32'd0;
    storage[103] = 32'd0;
    storage[104] = 32'd0;
    storage[105] = 32'd0;
    storage[106] = 32'd0;
    storage[107] = 32'd0;
    storage[108] = 32'd0;
    storage[109] = 32'd0;
    storage[110] = 32'd0;
    storage[111] = 32'd0;
    storage[112] = 32'd0;
    storage[113] = 32'd0;
    storage[114] = 32'd0;
    storage[115] = 32'd0;
    storage[116] = 32'd0;
    storage[117] = 32'd0;
    storage[118] = 32'd0;
    storage[119] = 32'd0;
    storage[120] = 32'd0;
    storage[121] = 32'd0;
    storage[122] = 32'd0;
    storage[123] = 32'd0;
    storage[124] = 32'd0;
    storage[125] = 32'd0;
    storage[126] = 32'd0;
    storage[127] = 32'd0;
    storage[128] = 32'd0;
    storage[129] = 32'd0;
    storage[130] = 32'd0;
    storage[131] = 32'd0;
    storage[132] = 32'd0;
    storage[133] = 32'd0;
    storage[134] = 32'd0;
    storage[135] = 32'd0;
    storage[136] = 32'd0;
    storage[137] = 32'd0;
    storage[138] = 32'd0;
    storage[139] = 32'd0;
    storage[140] = 32'd0;
    storage[141] = 32'd0;
    storage[142] = 32'd0;
    storage[143] = 32'd0;
    storage[144] = 32'd0;
    storage[145] = 32'd0;
    storage[146] = 32'd0;
    storage[147] = 32'd0;
    storage[148] = 32'd0;
    storage[149] = 32'd0;
    storage[150] = 32'd0;
    storage[151] = 32'd0;
    storage[152] = 32'd0;
    storage[153] = 32'd0;
    storage[154] = 32'd0;
    storage[155] = 32'd0;
    storage[156] = 32'd0;
    storage[157] = 32'd0;
    storage[158] = 32'd0;
    storage[159] = 32'd0;
    storage[160] = 32'd0;
    storage[161] = 32'd0;
    storage[162] = 32'd0;
    storage[163] = 32'd0;
    storage[164] = 32'd0;
    storage[165] = 32'd0;
    storage[166] = 32'd0;
    storage[167] = 32'd0;
    storage[168] = 32'd0;
    storage[169] = 32'd0;
    storage[170] = 32'd0;
    storage[171] = 32'd0;
    storage[172] = 32'd0;
    storage[173] = 32'd0;
    storage[174] = 32'd0;
    storage[175] = 32'd0;
    storage[176] = 32'd0;
    storage[177] = 32'd0;
    storage[178] = 32'd0;
    storage[179] = 32'd0;
    storage[180] = 32'd0;
    storage[181] = 32'd0;
    storage[182] = 32'd0;
    storage[183] = 32'd0;
    storage[184] = 32'd0;
    storage[185] = 32'd0;
    storage[186] = 32'd0;
    storage[187] = 32'd0;
    storage[188] = 32'd0;
    storage[189] = 32'd0;
    storage[190] = 32'd0;
    storage[191] = 32'd0;
    storage[192] = 32'd0;
    storage[193] = 32'd0;
    storage[194] = 32'd0;
    storage[195] = 32'd0;
    storage[196] = 32'd0;
    storage[197] = 32'd0;
    storage[198] = 32'd0;
    storage[199] = 32'd0;
    storage[200] = 32'd0;
    storage[201] = 32'd0;
    storage[202] = 32'd0;
    storage[203] = 32'd0;
    storage[204] = 32'd0;
    storage[205] = 32'd0;
    storage[206] = 32'd0;
    storage[207] = 32'd0;
    storage[208] = 32'd0;
    storage[209] = 32'd0;
    storage[210] = 32'd0;
    storage[211] = 32'd0;
    storage[212] = 32'd0;
    storage[213] = 32'd0;
    storage[214] = 32'd0;
    storage[215] = 32'd0;
    storage[216] = 32'd0;
    storage[217] = 32'd0;
    storage[218] = 32'd0;
    storage[219] = 32'd0;
    storage[220] = 32'd0;
    storage[221] = 32'd0;
    storage[222] = 32'd0;
    storage[223] = 32'd0;
    storage[224] = 32'd0;
    storage[225] = 32'd0;
    storage[226] = 32'd0;
    storage[227] = 32'd0;
    storage[228] = 32'd0;
    storage[229] = 32'd0;
    storage[230] = 32'd0;
    storage[231] = 32'd0;
    storage[232] = 32'd0;
    storage[233] = 32'd0;
    storage[234] = 32'd0;
    storage[235] = 32'd0;
    storage[236] = 32'd0;
    storage[237] = 32'd0;
    storage[238] = 32'd0;
    storage[239] = 32'd0;
    storage[240] = 32'd0;
    storage[241] = 32'd0;
    storage[242] = 32'd0;
    storage[243] = 32'd0;
    storage[244] = 32'd0;
    storage[245] = 32'd0;
    storage[246] = 32'd0;
    storage[247] = 32'd0;
    storage[248] = 32'd0;
    storage[249] = 32'd0;
    storage[250] = 32'd0;
    storage[251] = 32'd0;
    storage[252] = 32'd0;
    storage[253] = 32'd0;
    storage[254] = 32'd0;
    storage[255] = 32'd0;
    storage[256] = 32'd0;
    storage[257] = 32'd0;
    storage[258] = 32'd0;
    storage[259] = 32'd0;
    storage[260] = 32'd0;
    storage[261] = 32'd0;
    storage[262] = 32'd0;
    storage[263] = 32'd0;
    storage[264] = 32'd0;
    storage[265] = 32'd0;
    storage[266] = 32'd0;
    storage[267] = 32'd0;
    storage[268] = 32'd0;
    storage[269] = 32'd0;
    storage[270] = 32'd0;
    storage[271] = 32'd0;
    storage[272] = 32'd0;
    storage[273] = 32'd0;
    storage[274] = 32'd0;
    storage[275] = 32'd0;
    storage[276] = 32'd0;
    storage[277] = 32'd0;
    storage[278] = 32'd0;
    storage[279] = 32'd0;
    storage[280] = 32'd0;
    storage[281] = 32'd0;
    storage[282] = 32'd0;
    storage[283] = 32'd0;
    storage[284] = 32'd0;
    storage[285] = 32'd0;
    storage[286] = 32'd0;
    storage[287] = 32'd0;
    storage[288] = 32'd0;
    storage[289] = 32'd0;
    storage[290] = 32'd0;
    storage[291] = 32'd0;
    storage[292] = 32'd0;
    storage[293] = 32'd0;
    storage[294] = 32'd0;
    storage[295] = 32'd0;
    storage[296] = 32'd0;
    storage[297] = 32'd0;
    storage[298] = 32'd0;
    storage[299] = 32'd0;
    storage[300] = 32'd0;
    storage[301] = 32'd0;
    storage[302] = 32'd0;
    storage[303] = 32'd0;
    storage[304] = 32'd0;
    storage[305] = 32'd0;
    storage[306] = 32'd0;
    storage[307] = 32'd0;
    storage[308] = 32'd0;
    storage[309] = 32'd0;
    storage[310] = 32'd0;
    storage[311] = 32'd0;
    storage[312] = 32'd0;
    storage[313] = 32'd0;
    storage[314] = 32'd0;
    storage[315] = 32'd0;
    storage[316] = 32'd0;
    storage[317] = 32'd0;
    storage[318] = 32'd0;
    storage[319] = 32'd0;
    storage[320] = 32'd0;
    storage[321] = 32'd0;
    storage[322] = 32'd0;
    storage[323] = 32'd0;
    storage[324] = 32'd0;
    storage[325] = 32'd0;
    storage[326] = 32'd0;
    storage[327] = 32'd0;
    storage[328] = 32'd0;
    storage[329] = 32'd0;
    storage[330] = 32'd0;
    storage[331] = 32'd0;
    storage[332] = 32'd0;
    storage[333] = 32'd0;
    storage[334] = 32'd0;
    storage[335] = 32'd0;
    storage[336] = 32'd0;
    storage[337] = 32'd0;
    storage[338] = 32'd0;
    storage[339] = 32'd0;
    storage[340] = 32'd0;
    storage[341] = 32'd0;
    storage[342] = 32'd0;
    storage[343] = 32'd0;
    storage[344] = 32'd0;
    storage[345] = 32'd0;
    storage[346] = 32'd0;
    storage[347] = 32'd0;
    storage[348] = 32'd0;
    storage[349] = 32'd0;
    storage[350] = 32'd0;
    storage[351] = 32'd0;
    storage[352] = 32'd0;
    storage[353] = 32'd0;
    storage[354] = 32'd0;
    storage[355] = 32'd0;
    storage[356] = 32'd0;
    storage[357] = 32'd0;
    storage[358] = 32'd0;
    storage[359] = 32'd0;
    storage[360] = 32'd0;
    storage[361] = 32'd0;
    storage[362] = 32'd0;
    storage[363] = 32'd0;
    storage[364] = 32'd0;
    storage[365] = 32'd0;
    storage[366] = 32'd0;
    storage[367] = 32'd0;
    storage[368] = 32'd0;
    storage[369] = 32'd0;
    storage[370] = 32'd0;
    storage[371] = 32'd0;
    storage[372] = 32'd0;
    storage[373] = 32'd0;
    storage[374] = 32'd0;
    storage[375] = 32'd0;
    storage[376] = 32'd0;
    storage[377] = 32'd0;
    storage[378] = 32'd0;
    storage[379] = 32'd0;
    storage[380] = 32'd0;
    storage[381] = 32'd0;
    storage[382] = 32'd0;
    storage[383] = 32'd0;
    storage[384] = 32'd0;
    storage[385] = 32'd0;
    storage[386] = 32'd0;
    storage[387] = 32'd0;
    storage[388] = 32'd0;
    storage[389] = 32'd0;
    storage[390] = 32'd0;
    storage[391] = 32'd0;
    storage[392] = 32'd0;
    storage[393] = 32'd0;
    storage[394] = 32'd0;
    storage[395] = 32'd0;
    storage[396] = 32'd0;
    storage[397] = 32'd0;
    storage[398] = 32'd0;
    storage[399] = 32'd0;
    storage[400] = 32'd0;
    storage[401] = 32'd0;
    storage[402] = 32'd0;
    storage[403] = 32'd0;
    storage[404] = 32'd0;
    storage[405] = 32'd0;
    storage[406] = 32'd0;
    storage[407] = 32'd0;
    storage[408] = 32'd0;
    storage[409] = 32'd0;
    storage[410] = 32'd0;
    storage[411] = 32'd0;
    storage[412] = 32'd0;
    storage[413] = 32'd0;
    storage[414] = 32'd0;
    storage[415] = 32'd0;
    storage[416] = 32'd0;
    storage[417] = 32'd0;
    storage[418] = 32'd0;
    storage[419] = 32'd0;
    storage[420] = 32'd0;
    storage[421] = 32'd0;
    storage[422] = 32'd0;
    storage[423] = 32'd0;
    storage[424] = 32'd0;
    storage[425] = 32'd0;
    storage[426] = 32'd0;
    storage[427] = 32'd0;
    storage[428] = 32'd0;
    storage[429] = 32'd0;
    storage[430] = 32'd0;
    storage[431] = 32'd0;
    storage[432] = 32'd0;
    storage[433] = 32'd0;
    storage[434] = 32'd0;
    storage[435] = 32'd0;
    storage[436] = 32'd0;
    storage[437] = 32'd0;
    storage[438] = 32'd0;
    storage[439] = 32'd0;
    storage[440] = 32'd0;
    storage[441] = 32'd0;
    storage[442] = 32'd0;
    storage[443] = 32'd0;
    storage[444] = 32'd0;
    storage[445] = 32'd0;
    storage[446] = 32'd0;
    storage[447] = 32'd0;
    storage[448] = 32'd0;
    storage[449] = 32'd0;
    storage[450] = 32'd0;
    storage[451] = 32'd0;
    storage[452] = 32'd0;
    storage[453] = 32'd0;
    storage[454] = 32'd0;
    storage[455] = 32'd0;
    storage[456] = 32'd0;
    storage[457] = 32'd0;
    storage[458] = 32'd0;
    storage[459] = 32'd0;
    storage[460] = 32'd0;
    storage[461] = 32'd0;
    storage[462] = 32'd0;
    storage[463] = 32'd0;
    storage[464] = 32'd0;
    storage[465] = 32'd0;
    storage[466] = 32'd0;
    storage[467] = 32'd0;
    storage[468] = 32'd0;
    storage[469] = 32'd0;
    storage[470] = 32'd0;
    storage[471] = 32'd0;
    storage[472] = 32'd0;
    storage[473] = 32'd0;
    storage[474] = 32'd0;
    storage[475] = 32'd0;
    storage[476] = 32'd0;
    storage[477] = 32'd0;
    storage[478] = 32'd0;
    storage[479] = 32'd0;
    storage[480] = 32'd0;
    storage[481] = 32'd0;
    storage[482] = 32'd0;
    storage[483] = 32'd0;
    storage[484] = 32'd0;
    storage[485] = 32'd0;
    storage[486] = 32'd0;
    storage[487] = 32'd0;
    storage[488] = 32'd0;
    storage[489] = 32'd0;
    storage[490] = 32'd0;
    storage[491] = 32'd0;
    storage[492] = 32'd0;
    storage[493] = 32'd0;
    storage[494] = 32'd0;
    storage[495] = 32'd0;
    storage[496] = 32'd0;
    storage[497] = 32'd0;
    storage[498] = 32'd0;
    storage[499] = 32'd0;
    storage[500] = 32'd0;
    storage[501] = 32'd0;
    storage[502] = 32'd0;
    storage[503] = 32'd0;
    storage[504] = 32'd0;
    storage[505] = 32'd0;
    storage[506] = 32'd0;
    storage[507] = 32'd0;
    storage[508] = 32'd0;
    storage[509] = 32'd0;
    storage[510] = 32'd0;
    storage[511] = 32'd0;
    storage[512] = 32'd0;
    storage[513] = 32'd0;
    storage[514] = 32'd0;
    storage[515] = 32'd0;
    storage[516] = 32'd0;
    storage[517] = 32'd0;
    storage[518] = 32'd0;
    storage[519] = 32'd0;
    storage[520] = 32'd0;
    storage[521] = 32'd0;
    storage[522] = 32'd0;
    storage[523] = 32'd0;
    storage[524] = 32'd0;
    storage[525] = 32'd0;
    storage[526] = 32'd0;
    storage[527] = 32'd0;
    storage[528] = 32'd0;
    storage[529] = 32'd0;
    storage[530] = 32'd0;
    storage[531] = 32'd0;
    storage[532] = 32'd0;
    storage[533] = 32'd0;
    storage[534] = 32'd0;
    storage[535] = 32'd0;
    storage[536] = 32'd0;
    storage[537] = 32'd0;
    storage[538] = 32'd0;
    storage[539] = 32'd0;
    storage[540] = 32'd0;
    storage[541] = 32'd0;
    storage[542] = 32'd0;
    storage[543] = 32'd0;
    storage[544] = 32'd0;
    storage[545] = 32'd0;
    storage[546] = 32'd0;
    storage[547] = 32'd0;
    storage[548] = 32'd0;
    storage[549] = 32'd0;
    storage[550] = 32'd0;
    storage[551] = 32'd0;
    storage[552] = 32'd0;
    storage[553] = 32'd0;
    storage[554] = 32'd0;
    storage[555] = 32'd0;
    storage[556] = 32'd0;
    storage[557] = 32'd0;
    storage[558] = 32'd0;
    storage[559] = 32'd0;
    storage[560] = 32'd0;
    storage[561] = 32'd0;
    storage[562] = 32'd0;
    storage[563] = 32'd0;
    storage[564] = 32'd0;
    storage[565] = 32'd0;
    storage[566] = 32'd0;
    storage[567] = 32'd0;
    storage[568] = 32'd0;
    storage[569] = 32'd0;
    storage[570] = 32'd0;
    storage[571] = 32'd0;
    storage[572] = 32'd0;
    storage[573] = 32'd0;
    storage[574] = 32'd0;
    storage[575] = 32'd0;
    storage[576] = 32'd0;
    storage[577] = 32'd0;
    storage[578] = 32'd0;
    storage[579] = 32'd0;
    storage[580] = 32'd0;
    storage[581] = 32'd0;
    storage[582] = 32'd0;
    storage[583] = 32'd0;
    storage[584] = 32'd0;
    storage[585] = 32'd0;
    storage[586] = 32'd0;
    storage[587] = 32'd0;
    storage[588] = 32'd0;
    storage[589] = 32'd0;
    storage[590] = 32'd0;
    storage[591] = 32'd0;
    storage[592] = 32'd0;
    storage[593] = 32'd0;
    storage[594] = 32'd0;
    storage[595] = 32'd0;
    storage[596] = 32'd0;
    storage[597] = 32'd0;
    storage[598] = 32'd0;
    storage[599] = 32'd0;
    storage[600] = 32'd0;
    storage[601] = 32'd0;
    storage[602] = 32'd0;
    storage[603] = 32'd0;
    storage[604] = 32'd0;
    storage[605] = 32'd0;
    storage[606] = 32'd0;
    storage[607] = 32'd0;
    storage[608] = 32'd0;
    storage[609] = 32'd0;
    storage[610] = 32'd0;
    storage[611] = 32'd0;
    storage[612] = 32'd0;
    storage[613] = 32'd0;
    storage[614] = 32'd0;
    storage[615] = 32'd0;
    storage[616] = 32'd0;
    storage[617] = 32'd0;
    storage[618] = 32'd0;
    storage[619] = 32'd0;
    storage[620] = 32'd0;
    storage[621] = 32'd0;
    storage[622] = 32'd0;
    storage[623] = 32'd0;
    storage[624] = 32'd0;
    storage[625] = 32'd0;
    storage[626] = 32'd0;
    storage[627] = 32'd0;
    storage[628] = 32'd0;
    storage[629] = 32'd0;
    storage[630] = 32'd0;
    storage[631] = 32'd0;
    storage[632] = 32'd0;
    storage[633] = 32'd0;
    storage[634] = 32'd0;
    storage[635] = 32'd0;
    storage[636] = 32'd0;
    storage[637] = 32'd0;
    storage[638] = 32'd0;
    storage[639] = 32'd0;
    storage[640] = 32'd0;
    storage[641] = 32'd0;
    storage[642] = 32'd0;
    storage[643] = 32'd0;
    storage[644] = 32'd0;
    storage[645] = 32'd0;
    storage[646] = 32'd0;
    storage[647] = 32'd0;
    storage[648] = 32'd0;
    storage[649] = 32'd0;
    storage[650] = 32'd0;
    storage[651] = 32'd0;
    storage[652] = 32'd0;
    storage[653] = 32'd0;
    storage[654] = 32'd0;
    storage[655] = 32'd0;
    storage[656] = 32'd0;
    storage[657] = 32'd0;
    storage[658] = 32'd0;
    storage[659] = 32'd0;
    storage[660] = 32'd0;
    storage[661] = 32'd0;
    storage[662] = 32'd0;
    storage[663] = 32'd0;
    storage[664] = 32'd0;
    storage[665] = 32'd0;
    storage[666] = 32'd0;
    storage[667] = 32'd0;
    storage[668] = 32'd0;
    storage[669] = 32'd0;
    storage[670] = 32'd0;
    storage[671] = 32'd0;
    storage[672] = 32'd0;
    storage[673] = 32'd0;
    storage[674] = 32'd0;
    storage[675] = 32'd0;
    storage[676] = 32'd0;
    storage[677] = 32'd0;
    storage[678] = 32'd0;
    storage[679] = 32'd0;
    storage[680] = 32'd0;
    storage[681] = 32'd0;
    storage[682] = 32'd0;
    storage[683] = 32'd0;
    storage[684] = 32'd0;
    storage[685] = 32'd0;
    storage[686] = 32'd0;
    storage[687] = 32'd0;
    storage[688] = 32'd0;
    storage[689] = 32'd0;
    storage[690] = 32'd0;
    storage[691] = 32'd0;
    storage[692] = 32'd0;
    storage[693] = 32'd0;
    storage[694] = 32'd0;
    storage[695] = 32'd0;
    storage[696] = 32'd0;
    storage[697] = 32'd0;
    storage[698] = 32'd0;
    storage[699] = 32'd0;
    storage[700] = 32'd0;
    storage[701] = 32'd0;
    storage[702] = 32'd0;
    storage[703] = 32'd0;
    storage[704] = 32'd0;
    storage[705] = 32'd0;
    storage[706] = 32'd0;
    storage[707] = 32'd0;
    storage[708] = 32'd0;
    storage[709] = 32'd0;
    storage[710] = 32'd0;
    storage[711] = 32'd0;
    storage[712] = 32'd0;
    storage[713] = 32'd0;
    storage[714] = 32'd0;
    storage[715] = 32'd0;
    storage[716] = 32'd0;
    storage[717] = 32'd0;
    storage[718] = 32'd0;
    storage[719] = 32'd0;
    storage[720] = 32'd0;
    storage[721] = 32'd0;
    storage[722] = 32'd0;
    storage[723] = 32'd0;
    storage[724] = 32'd0;
    storage[725] = 32'd0;
    storage[726] = 32'd0;
    storage[727] = 32'd0;
    storage[728] = 32'd0;
    storage[729] = 32'd0;
    storage[730] = 32'd0;
    storage[731] = 32'd0;
    storage[732] = 32'd0;
    storage[733] = 32'd0;
    storage[734] = 32'd0;
    storage[735] = 32'd0;
    storage[736] = 32'd0;
    storage[737] = 32'd0;
    storage[738] = 32'd0;
    storage[739] = 32'd0;
    storage[740] = 32'd0;
    storage[741] = 32'd0;
    storage[742] = 32'd0;
    storage[743] = 32'd0;
    storage[744] = 32'd0;
    storage[745] = 32'd0;
    storage[746] = 32'd0;
    storage[747] = 32'd0;
    storage[748] = 32'd0;
    storage[749] = 32'd0;
    storage[750] = 32'd0;
    storage[751] = 32'd0;
    storage[752] = 32'd0;
    storage[753] = 32'd0;
    storage[754] = 32'd0;
    storage[755] = 32'd0;
    storage[756] = 32'd0;
    storage[757] = 32'd0;
    storage[758] = 32'd0;
    storage[759] = 32'd0;
    storage[760] = 32'd0;
    storage[761] = 32'd0;
    storage[762] = 32'd0;
    storage[763] = 32'd0;
    storage[764] = 32'd0;
    storage[765] = 32'd0;
    storage[766] = 32'd0;
    storage[767] = 32'd0;
    storage[768] = 32'd0;
    storage[769] = 32'd0;
    storage[770] = 32'd0;
    storage[771] = 32'd0;
    storage[772] = 32'd0;
    storage[773] = 32'd0;
    storage[774] = 32'd0;
    storage[775] = 32'd0;
    storage[776] = 32'd0;
    storage[777] = 32'd0;
    storage[778] = 32'd0;
    storage[779] = 32'd0;
    storage[780] = 32'd0;
    storage[781] = 32'd0;
    storage[782] = 32'd0;
    storage[783] = 32'd0;
    storage[784] = 32'd0;
    storage[785] = 32'd0;
    storage[786] = 32'd0;
    storage[787] = 32'd0;
    storage[788] = 32'd0;
    storage[789] = 32'd0;
    storage[790] = 32'd0;
    storage[791] = 32'd0;
    storage[792] = 32'd0;
    storage[793] = 32'd0;
    storage[794] = 32'd0;
    storage[795] = 32'd0;
    storage[796] = 32'd0;
    storage[797] = 32'd0;
    storage[798] = 32'd0;
    storage[799] = 32'd0;
    storage[800] = 32'd0;
    storage[801] = 32'd0;
    storage[802] = 32'd0;
    storage[803] = 32'd0;
    storage[804] = 32'd0;
    storage[805] = 32'd0;
    storage[806] = 32'd0;
    storage[807] = 32'd0;
    storage[808] = 32'd0;
    storage[809] = 32'd0;
    storage[810] = 32'd0;
    storage[811] = 32'd0;
    storage[812] = 32'd0;
    storage[813] = 32'd0;
    storage[814] = 32'd0;
    storage[815] = 32'd0;
    storage[816] = 32'd0;
    storage[817] = 32'd0;
    storage[818] = 32'd0;
    storage[819] = 32'd0;
    storage[820] = 32'd0;
    storage[821] = 32'd0;
    storage[822] = 32'd0;
    storage[823] = 32'd0;
    storage[824] = 32'd0;
    storage[825] = 32'd0;
    storage[826] = 32'd0;
    storage[827] = 32'd0;
    storage[828] = 32'd0;
    storage[829] = 32'd0;
    storage[830] = 32'd0;
    storage[831] = 32'd0;
    storage[832] = 32'd0;
    storage[833] = 32'd0;
    storage[834] = 32'd0;
    storage[835] = 32'd0;
    storage[836] = 32'd0;
    storage[837] = 32'd0;
    storage[838] = 32'd0;
    storage[839] = 32'd0;
    storage[840] = 32'd0;
    storage[841] = 32'd0;
    storage[842] = 32'd0;
    storage[843] = 32'd0;
    storage[844] = 32'd0;
    storage[845] = 32'd0;
    storage[846] = 32'd0;
    storage[847] = 32'd0;
    storage[848] = 32'd0;
    storage[849] = 32'd0;
    storage[850] = 32'd0;
    storage[851] = 32'd0;
    storage[852] = 32'd0;
    storage[853] = 32'd0;
    storage[854] = 32'd0;
    storage[855] = 32'd0;
    storage[856] = 32'd0;
    storage[857] = 32'd0;
    storage[858] = 32'd0;
    storage[859] = 32'd0;
    storage[860] = 32'd0;
    storage[861] = 32'd0;
    storage[862] = 32'd0;
    storage[863] = 32'd0;
    storage[864] = 32'd0;
    storage[865] = 32'd0;
    storage[866] = 32'd0;
    storage[867] = 32'd0;
    storage[868] = 32'd0;
    storage[869] = 32'd0;
    storage[870] = 32'd0;
    storage[871] = 32'd0;
    storage[872] = 32'd0;
    storage[873] = 32'd0;
    storage[874] = 32'd0;
    storage[875] = 32'd0;
    storage[876] = 32'd0;
    storage[877] = 32'd0;
    storage[878] = 32'd0;
    storage[879] = 32'd0;
    storage[880] = 32'd0;
    storage[881] = 32'd0;
    storage[882] = 32'd0;
    storage[883] = 32'd0;
    storage[884] = 32'd0;
    storage[885] = 32'd0;
    storage[886] = 32'd0;
    storage[887] = 32'd0;
    storage[888] = 32'd0;
    storage[889] = 32'd0;
    storage[890] = 32'd0;
    storage[891] = 32'd0;
    storage[892] = 32'd0;
    storage[893] = 32'd0;
    storage[894] = 32'd0;
    storage[895] = 32'd0;
    storage[896] = 32'd0;
    storage[897] = 32'd0;
    storage[898] = 32'd0;
    storage[899] = 32'd0;
    storage[900] = 32'd0;
    storage[901] = 32'd0;
    storage[902] = 32'd0;
    storage[903] = 32'd0;
    storage[904] = 32'd0;
    storage[905] = 32'd0;
    storage[906] = 32'd0;
    storage[907] = 32'd0;
    storage[908] = 32'd0;
    storage[909] = 32'd0;
    storage[910] = 32'd0;
    storage[911] = 32'd0;
    storage[912] = 32'd0;
    storage[913] = 32'd0;
    storage[914] = 32'd0;
    storage[915] = 32'd0;
    storage[916] = 32'd0;
    storage[917] = 32'd0;
    storage[918] = 32'd0;
    storage[919] = 32'd0;
    storage[920] = 32'd0;
    storage[921] = 32'd0;
    storage[922] = 32'd0;
    storage[923] = 32'd0;
    storage[924] = 32'd0;
    storage[925] = 32'd0;
    storage[926] = 32'd0;
    storage[927] = 32'd0;
    storage[928] = 32'd0;
    storage[929] = 32'd0;
    storage[930] = 32'd0;
    storage[931] = 32'd0;
    storage[932] = 32'd0;
    storage[933] = 32'd0;
    storage[934] = 32'd0;
    storage[935] = 32'd0;
    storage[936] = 32'd0;
    storage[937] = 32'd0;
    storage[938] = 32'd0;
    storage[939] = 32'd0;
    storage[940] = 32'd0;
    storage[941] = 32'd0;
    storage[942] = 32'd0;
    storage[943] = 32'd0;
    storage[944] = 32'd0;
    storage[945] = 32'd0;
    storage[946] = 32'd0;
    storage[947] = 32'd0;
    storage[948] = 32'd0;
    storage[949] = 32'd0;
    storage[950] = 32'd0;
    storage[951] = 32'd0;
    storage[952] = 32'd0;
    storage[953] = 32'd0;
    storage[954] = 32'd0;
    storage[955] = 32'd0;
    storage[956] = 32'd0;
    storage[957] = 32'd0;
    storage[958] = 32'd0;
    storage[959] = 32'd0;
    storage[960] = 32'd0;
    storage[961] = 32'd0;
    storage[962] = 32'd0;
    storage[963] = 32'd0;
    storage[964] = 32'd0;
    storage[965] = 32'd0;
    storage[966] = 32'd0;
    storage[967] = 32'd0;
    storage[968] = 32'd0;
    storage[969] = 32'd0;
    storage[970] = 32'd0;
    storage[971] = 32'd0;
    storage[972] = 32'd0;
    storage[973] = 32'd0;
    storage[974] = 32'd0;
    storage[975] = 32'd0;
    storage[976] = 32'd0;
    storage[977] = 32'd0;
    storage[978] = 32'd0;
    storage[979] = 32'd0;
    storage[980] = 32'd0;
    storage[981] = 32'd0;
    storage[982] = 32'd0;
    storage[983] = 32'd0;
    storage[984] = 32'd0;
    storage[985] = 32'd0;
    storage[986] = 32'd0;
    storage[987] = 32'd0;
    storage[988] = 32'd0;
    storage[989] = 32'd0;
    storage[990] = 32'd0;
    storage[991] = 32'd0;
    storage[992] = 32'd0;
    storage[993] = 32'd0;
    storage[994] = 32'd0;
    storage[995] = 32'd0;
    storage[996] = 32'd0;
    storage[997] = 32'd0;
    storage[998] = 32'd0;
    storage[999] = 32'd0;
    storage[1000] = 32'd0;
    storage[1001] = 32'd0;
    storage[1002] = 32'd0;
    storage[1003] = 32'd0;
    storage[1004] = 32'd0;
    storage[1005] = 32'd0;
    storage[1006] = 32'd0;
    storage[1007] = 32'd0;
    storage[1008] = 32'd0;
    storage[1009] = 32'd0;
    storage[1010] = 32'd0;
    storage[1011] = 32'd0;
    storage[1012] = 32'd0;
    storage[1013] = 32'd0;
    storage[1014] = 32'd0;
    storage[1015] = 32'd0;
    storage[1016] = 32'd0;
    storage[1017] = 32'd0;
    storage[1018] = 32'd0;
    storage[1019] = 32'd0;
    storage[1020] = 32'd0;
    storage[1021] = 32'd0;
    storage[1022] = 32'd0;
    storage[1023] = 32'd0;
  end
  always @(posedge eq_clk) begin
    if (w_port__en)
      storage[produce_w_bin[9:0]] <= w_port__data;
  end
  reg [31:0] _0_;
  always @(posedge clk) begin
    _0_ <= storage[\$4 [9:0]];
  end
  assign r_data = _0_;
  assign \$1  = w_rdy & w_en;
  assign \$2  = produce_w_bin + \$1 ;
  assign \$3  = r_rdy & r_en;
  assign \$4  = consume_r_bin + \$3 ;
  assign \$6  = \$5  ^ produce_r_gry[9];
  assign \$7  = \$6  ^ produce_r_gry[8];
  assign \$8  = \$7  ^ produce_r_gry[7];
  assign \$9  = \$8  ^ produce_r_gry[6];
  assign \$10  = \$9  ^ produce_r_gry[5];
  assign \$11  = \$10  ^ produce_r_gry[4];
  assign \$12  = \$11  ^ produce_r_gry[3];
  assign \$13  = \$12  ^ produce_r_gry[2];
  assign \$14  = \$13  ^ produce_r_gry[1];
  assign \$15  = \$14  ^ produce_r_gry[0];
  assign \$17  = \$16  ^ produce_r_gry[9];
  assign \$18  = \$17  ^ produce_r_gry[8];
  assign \$19  = \$18  ^ produce_r_gry[7];
  assign \$20  = \$19  ^ produce_r_gry[6];
  assign \$21  = \$20  ^ produce_r_gry[5];
  assign \$22  = \$21  ^ produce_r_gry[4];
  assign \$23  = \$22  ^ produce_r_gry[3];
  assign \$24  = \$23  ^ produce_r_gry[2];
  assign \$25  = \$24  ^ produce_r_gry[1];
  assign \$27  = \$26  ^ produce_r_gry[9];
  assign \$28  = \$27  ^ produce_r_gry[8];
  assign \$29  = \$28  ^ produce_r_gry[7];
  assign \$30  = \$29  ^ produce_r_gry[6];
  assign \$31  = \$30  ^ produce_r_gry[5];
  assign \$32  = \$31  ^ produce_r_gry[4];
  assign \$33  = \$32  ^ produce_r_gry[3];
  assign \$34  = \$33  ^ produce_r_gry[2];
  assign \$36  = \$35  ^ produce_r_gry[9];
  assign \$37  = \$36  ^ produce_r_gry[8];
  assign \$38  = \$37  ^ produce_r_gry[7];
  assign \$39  = \$38  ^ produce_r_gry[6];
  assign \$40  = \$39  ^ produce_r_gry[5];
  assign \$41  = \$40  ^ produce_r_gry[4];
  assign \$42  = \$41  ^ produce_r_gry[3];
  assign \$44  = \$43  ^ produce_r_gry[9];
  assign \$45  = \$44  ^ produce_r_gry[8];
  assign \$46  = \$45  ^ produce_r_gry[7];
  assign \$47  = \$46  ^ produce_r_gry[6];
  assign \$48  = \$47  ^ produce_r_gry[5];
  assign \$49  = \$48  ^ produce_r_gry[4];
  assign \$51  = \$50  ^ produce_r_gry[9];
  assign \$52  = \$51  ^ produce_r_gry[8];
  assign \$53  = \$52  ^ produce_r_gry[7];
  assign \$54  = \$53  ^ produce_r_gry[6];
  assign \$55  = \$54  ^ produce_r_gry[5];
  assign \$57  = \$56  ^ produce_r_gry[9];
  assign \$58  = \$57  ^ produce_r_gry[8];
  assign \$59  = \$58  ^ produce_r_gry[7];
  assign \$60  = \$59  ^ produce_r_gry[6];
  assign \$62  = \$61  ^ produce_r_gry[9];
  assign \$63  = \$62  ^ produce_r_gry[8];
  assign \$64  = \$63  ^ produce_r_gry[7];
  assign \$66  = \$65  ^ produce_r_gry[9];
  assign \$67  = \$66  ^ produce_r_gry[8];
  assign \$69  = \$68  ^ produce_r_gry[9];
  assign \$71  = produce_w_gry[10] != consume_w_gry[10];
  assign \$72  = produce_w_gry[9] != consume_w_gry[9];
  assign \$73  = \$71  & \$72 ;
  assign \$74  = produce_w_gry[8:0] == consume_w_gry[8:0];
  assign w_full = \$73  & \$74 ;
  assign \$75  = consume_r_gry == produce_r_gry;
  assign \$76  = { \$70 , \$69 , \$67 , \$64 , \$60 , \$55 , \$49 , \$42 , \$34 , \$25 , \$15  } - consume_r_bin;
  assign w_port__en = w_rdy & w_en;
  assign w_rdy = ~ w_full;
  assign r_rdy = ~ r_empty;
  assign \$77  = \$2 [10:0] ^ { 1'h0, \$2 [10:1] };
  assign \$79  = \$78  ^ consume_w_gry[9];
  assign \$80  = \$79  ^ consume_w_gry[8];
  assign \$81  = \$80  ^ consume_w_gry[7];
  assign \$82  = \$81  ^ consume_w_gry[6];
  assign \$83  = \$82  ^ consume_w_gry[5];
  assign \$84  = \$83  ^ consume_w_gry[4];
  assign \$85  = \$84  ^ consume_w_gry[3];
  assign \$86  = \$85  ^ consume_w_gry[2];
  assign \$87  = \$86  ^ consume_w_gry[1];
  assign \$88  = \$87  ^ consume_w_gry[0];
  assign \$90  = \$89  ^ consume_w_gry[9];
  assign \$91  = \$90  ^ consume_w_gry[8];
  assign \$92  = \$91  ^ consume_w_gry[7];
  assign \$93  = \$92  ^ consume_w_gry[6];
  assign \$94  = \$93  ^ consume_w_gry[5];
  assign \$95  = \$94  ^ consume_w_gry[4];
  assign \$96  = \$95  ^ consume_w_gry[3];
  assign \$97  = \$96  ^ consume_w_gry[2];
  assign \$98  = \$97  ^ consume_w_gry[1];
  assign \$100  = \$99  ^ consume_w_gry[9];
  assign \$101  = \$100  ^ consume_w_gry[8];
  assign \$102  = \$101  ^ consume_w_gry[7];
  assign \$103  = \$102  ^ consume_w_gry[6];
  assign \$104  = \$103  ^ consume_w_gry[5];
  assign \$105  = \$104  ^ consume_w_gry[4];
  assign \$106  = \$105  ^ consume_w_gry[3];
  assign \$107  = \$106  ^ consume_w_gry[2];
  assign \$109  = \$108  ^ consume_w_gry[9];
  assign \$110  = \$109  ^ consume_w_gry[8];
  assign \$111  = \$110  ^ consume_w_gry[7];
  assign \$112  = \$111  ^ consume_w_gry[6];
  assign \$113  = \$112  ^ consume_w_gry[5];
  assign \$114  = \$113  ^ consume_w_gry[4];
  assign \$115  = \$114  ^ consume_w_gry[3];
  assign \$117  = \$116  ^ consume_w_gry[9];
  assign \$118  = \$117  ^ consume_w_gry[8];
  assign \$119  = \$118  ^ consume_w_gry[7];
  assign \$120  = \$119  ^ consume_w_gry[6];
  assign \$121  = \$120  ^ consume_w_gry[5];
  assign \$122  = \$121  ^ consume_w_gry[4];
  assign \$124  = \$123  ^ consume_w_gry[9];
  assign \$125  = \$124  ^ consume_w_gry[8];
  assign \$126  = \$125  ^ consume_w_gry[7];
  assign \$127  = \$126  ^ consume_w_gry[6];
  assign \$128  = \$127  ^ consume_w_gry[5];
  assign \$130  = \$129  ^ consume_w_gry[9];
  assign \$131  = \$130  ^ consume_w_gry[8];
  assign \$132  = \$131  ^ consume_w_gry[7];
  assign \$133  = \$132  ^ consume_w_gry[6];
  assign \$135  = \$134  ^ consume_w_gry[9];
  assign \$136  = \$135  ^ consume_w_gry[8];
  assign \$137  = \$136  ^ consume_w_gry[7];
  assign \$139  = \$138  ^ consume_w_gry[9];
  assign \$140  = \$139  ^ consume_w_gry[8];
  assign \$142  = \$141  ^ consume_w_gry[9];
  assign \$144  = produce_w_bin - consume_w_bin;
  assign \$145  = \$4 [10:0] ^ { 1'h0, \$4 [10:1] };
  assign \$147  = \$146  ^ produce_r_gry[9];
  assign \$148  = \$147  ^ produce_r_gry[8];
  assign \$149  = \$148  ^ produce_r_gry[7];
  assign \$150  = \$149  ^ produce_r_gry[6];
  assign \$151  = \$150  ^ produce_r_gry[5];
  assign \$152  = \$151  ^ produce_r_gry[4];
  assign \$153  = \$152  ^ produce_r_gry[3];
  assign \$154  = \$153  ^ produce_r_gry[2];
  assign \$155  = \$154  ^ produce_r_gry[1];
  assign \$156  = \$155  ^ produce_r_gry[0];
  assign \$158  = \$157  ^ produce_r_gry[9];
  assign \$159  = \$158  ^ produce_r_gry[8];
  assign \$160  = \$159  ^ produce_r_gry[7];
  assign \$161  = \$160  ^ produce_r_gry[6];
  assign \$162  = \$161  ^ produce_r_gry[5];
  assign \$163  = \$162  ^ produce_r_gry[4];
  assign \$164  = \$163  ^ produce_r_gry[3];
  assign \$165  = \$164  ^ produce_r_gry[2];
  assign \$166  = \$165  ^ produce_r_gry[1];
  assign \$168  = \$167  ^ produce_r_gry[9];
  assign \$169  = \$168  ^ produce_r_gry[8];
  assign \$170  = \$169  ^ produce_r_gry[7];
  assign \$171  = \$170  ^ produce_r_gry[6];
  assign \$172  = \$171  ^ produce_r_gry[5];
  assign \$173  = \$172  ^ produce_r_gry[4];
  assign \$174  = \$173  ^ produce_r_gry[3];
  assign \$175  = \$174  ^ produce_r_gry[2];
  assign \$177  = \$176  ^ produce_r_gry[9];
  assign \$178  = \$177  ^ produce_r_gry[8];
  assign \$179  = \$178  ^ produce_r_gry[7];
  assign \$180  = \$179  ^ produce_r_gry[6];
  assign \$181  = \$180  ^ produce_r_gry[5];
  assign \$182  = \$181  ^ produce_r_gry[4];
  assign \$183  = \$182  ^ produce_r_gry[3];
  assign \$185  = \$184  ^ produce_r_gry[9];
  assign \$186  = \$185  ^ produce_r_gry[8];
  assign \$187  = \$186  ^ produce_r_gry[7];
  assign \$188  = \$187  ^ produce_r_gry[6];
  assign \$189  = \$188  ^ produce_r_gry[5];
  assign \$190  = \$189  ^ produce_r_gry[4];
  assign \$192  = \$191  ^ produce_r_gry[9];
  assign \$193  = \$192  ^ produce_r_gry[8];
  assign \$194  = \$193  ^ produce_r_gry[7];
  assign \$195  = \$194  ^ produce_r_gry[6];
  assign \$196  = \$195  ^ produce_r_gry[5];
  assign \$198  = \$197  ^ produce_r_gry[9];
  assign \$199  = \$198  ^ produce_r_gry[8];
  assign \$200  = \$199  ^ produce_r_gry[7];
  assign \$201  = \$200  ^ produce_r_gry[6];
  assign \$203  = \$202  ^ produce_r_gry[9];
  assign \$204  = \$203  ^ produce_r_gry[8];
  assign \$205  = \$204  ^ produce_r_gry[7];
  assign \$207  = \$206  ^ produce_r_gry[9];
  assign \$208  = \$207  ^ produce_r_gry[8];
  assign \$210  = \$209  ^ produce_r_gry[9];
  always @(posedge eq_clk)
    produce_w_bin <= \$212 ;
  always @(posedge eq_clk)
    produce_w_gry <= \$213 ;
  always @(posedge eq_clk)
    consume_w_bin <= \$214 ;
  always @(posedge eq_clk)
    w_level <= \$215 ;
  always @(posedge clk)
    consume_r_bin <= \$216 ;
  always @(posedge clk)
    consume_r_gry <= \$217 ;
  always @(posedge clk)
    \r_rst$31  <= \$218 ;
  \t2router.cdc.consume_cdc  consume_cdc (
    .consume_r_gry(consume_r_gry),
    .eq_clk(eq_clk),
    .eq_rst(eq_rst),
    .stage1(consume_w_gry)
  );
  \t2router.cdc.produce_cdc  produce_cdc (
    .clk(clk),
    .produce_w_gry(produce_w_gry),
    .rst(rst),
    .stage1(produce_r_gry)
  );
  \t2router.cdc.rst_cdc  rst_cdc (
    .async_ff_clk(clk),
    .async_ff_rst(eq_rst),
    .stage1(r_rst)
  );
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$2 ) begin end
    r_empty = \$75 ;
    if (r_rst) begin
      r_empty = 1'h1;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$2 ) begin end
    \$212  = \$2 [10:0];
    if (eq_rst) begin
      \$212  = 11'h000;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$2 ) begin end
    \$213  = \$77 ;
    if (eq_rst) begin
      \$213  = 11'h000;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$2 ) begin end
    \$214  = { \$143 , \$142 , \$140 , \$137 , \$133 , \$128 , \$122 , \$115 , \$107 , \$98 , \$88  };
    if (eq_rst) begin
      \$214  = 11'h000;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$2 ) begin end
    \$215  = \$144 [10:0];
    if (eq_rst) begin
      \$215  = 11'h000;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$2 ) begin end
    \$216  = \$4 [10:0];
    if (r_rst) begin
      \$216  = { \$211 , \$210 , \$208 , \$205 , \$201 , \$196 , \$190 , \$183 , \$175 , \$166 , \$156  };
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$2 ) begin end
    \$217  = \$145 ;
    if (r_rst) begin
      \$217  = produce_r_gry;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$2 ) begin end
    (* full_case = 32'd1 *)
    if (r_rst) begin
      \$218  = 1'h1;
    end else begin
      \$218  = 1'h0;
    end
    if (rst) begin
      \$218  = 1'h0;
    end
  end
  assign produce_w_nxt = \$2 [10:0];
  assign consume_r_nxt = \$4 [10:0];
  assign produce_r_bin = { \$70 , \$69 , \$67 , \$64 , \$60 , \$55 , \$49 , \$42 , \$34 , \$25 , \$15  };
  assign r_level = \$76 [10:0];
  assign w_port__addr = produce_w_bin[9:0];
  assign w_data = w_port__data;
  assign r_port__addr = \$4 [9:0];
  assign r_port__data = r_data;
  assign r_port__en = 1'h1;
  assign \$5  = produce_r_gry[10];
  assign \$16  = produce_r_gry[10];
  assign \$26  = produce_r_gry[10];
  assign \$35  = produce_r_gry[10];
  assign \$43  = produce_r_gry[10];
  assign \$50  = produce_r_gry[10];
  assign \$56  = produce_r_gry[10];
  assign \$61  = produce_r_gry[10];
  assign \$65  = produce_r_gry[10];
  assign \$68  = produce_r_gry[10];
  assign \$70  = produce_r_gry[10];
  assign \$78  = consume_w_gry[10];
  assign \$89  = consume_w_gry[10];
  assign \$99  = consume_w_gry[10];
  assign \$108  = consume_w_gry[10];
  assign \$116  = consume_w_gry[10];
  assign \$123  = consume_w_gry[10];
  assign \$129  = consume_w_gry[10];
  assign \$134  = consume_w_gry[10];
  assign \$138  = consume_w_gry[10];
  assign \$141  = consume_w_gry[10];
  assign \$143  = consume_w_gry[10];
  assign \$146  = produce_r_gry[10];
  assign \$157  = produce_r_gry[10];
  assign \$167  = produce_r_gry[10];
  assign \$176  = produce_r_gry[10];
  assign \$184  = produce_r_gry[10];
  assign \$191  = produce_r_gry[10];
  assign \$197  = produce_r_gry[10];
  assign \$202  = produce_r_gry[10];
  assign \$206  = produce_r_gry[10];
  assign \$209  = produce_r_gry[10];
  assign \$211  = produce_r_gry[10];
endmodule

(* generator = "Amaranth" *)
module \t2router.cdc.consume_cdc (eq_rst, consume_r_gry, stage1, eq_clk);
  input [10:0] consume_r_gry;
  wire [10:0] consume_r_gry;
  (* init = 11'h000 *)
  wire [10:0] consume_w_gry;
  input eq_clk;
  wire eq_clk;
  input eq_rst;
  wire eq_rst;
  reg [10:0] stage0 = 11'h000;
  output [10:0] stage1;
  reg [10:0] stage1 = 11'h000;
  always @(posedge eq_clk)
    stage0 <= consume_r_gry;
  always @(posedge eq_clk)
    stage1 <= stage0;
  assign consume_w_gry = stage1;
endmodule

(* generator = "Amaranth" *)
module \t2router.cdc.produce_cdc (rst, produce_w_gry, stage1, clk);
  input clk;
  wire clk;
  (* init = 11'h000 *)
  wire [10:0] produce_r_gry;
  input [10:0] produce_w_gry;
  wire [10:0] produce_w_gry;
  input rst;
  wire rst;
  reg [10:0] stage0 = 11'h000;
  output [10:0] stage1;
  reg [10:0] stage1 = 11'h000;
  always @(posedge clk)
    stage0 <= produce_w_gry;
  always @(posedge clk)
    stage1 <= stage0;
  assign produce_r_gry = stage1;
endmodule

(* generator = "Amaranth" *)
module \t2router.cdc.rst_cdc (async_ff_clk, stage1, async_ff_rst);
  input async_ff_clk;
  wire async_ff_clk;
  input async_ff_rst;
  wire async_ff_rst;
  wire clk;
  wire eq_rst;
  (* init = 1'h1 *)
  wire r_rst;
  reg stage0 = 1'h1;
  output stage1;
  reg stage1 = 1'h1;
  always @(posedge async_ff_clk, posedge async_ff_rst)
    if (async_ff_rst) stage0 <= 1'h1;
    else stage0 <= 1'h0;
  always @(posedge async_ff_clk, posedge async_ff_rst)
    if (async_ff_rst) stage1 <= 1'h1;
    else stage1 <= stage0;
  assign eq_rst = async_ff_rst;
  assign clk = async_ff_clk;
  assign r_rst = stage1;
endmodule

(* generator = "Amaranth" *)
module \t2router.tfifo (w_en, clk, rst, w_rdy, w_level, r_data, r_en, r_rdy, w_port__data);
  reg \$auto$verilog_backend.cc:2355:dump_module$3  = 0;
  wire \$1 ;
  wire \$10 ;
  wire [6:0] \$11 ;
  wire [6:0] \$12 ;
  wire \$13 ;
  wire \$14 ;
  wire \$15 ;
  wire \$16 ;
  wire \$17 ;
  wire \$18 ;
  wire [6:0] \$19 ;
  wire \$2 ;
  wire \$20 ;
  wire \$21 ;
  wire \$22 ;
  wire \$23 ;
  wire \$24 ;
  wire \$25 ;
  wire [6:0] \$26 ;
  wire \$27 ;
  wire \$28 ;
  wire \$29 ;
  wire \$3 ;
  reg [5:0] \$30 ;
  reg [5:0] \$31 ;
  reg [5:0] \$32 ;
  reg \$33 ;
  wire \$4 ;
  wire [6:0] \$5 ;
  wire [6:0] \$6 ;
  wire \$7 ;
  wire \$8 ;
  wire \$9 ;
  input clk;
  wire clk;
  (* init = 6'h00 *)
  wire [5:0] consume;
  reg [5:0] inner_level = 6'h00;
  wire inner_r_rdy;
  wire [6:0] level;
  (* init = 6'h00 *)
  wire [5:0] produce;
  output [63:0] r_data;
  wire [63:0] r_data;
  input r_en;
  wire r_en;
  wire [6:0] r_level;
  reg [5:0] r_port__addr = 6'h00;
  wire [63:0] r_port__data;
  wire r_port__en;
  output r_rdy;
  reg r_rdy = 1'h0;
  input rst;
  wire rst;
  wire [63:0] w_data;
  input w_en;
  wire w_en;
  output [6:0] w_level;
  wire [6:0] w_level;
  reg [5:0] w_port__addr = 6'h00;
  input [63:0] w_port__data;
  wire [63:0] w_port__data;
  wire w_port__en;
  output w_rdy;
  wire w_rdy;
  reg [63:0] storage [62:0];
  initial begin
    storage[0] = 64'h0000000000000000;
    storage[1] = 64'h0000000000000000;
    storage[2] = 64'h0000000000000000;
    storage[3] = 64'h0000000000000000;
    storage[4] = 64'h0000000000000000;
    storage[5] = 64'h0000000000000000;
    storage[6] = 64'h0000000000000000;
    storage[7] = 64'h0000000000000000;
    storage[8] = 64'h0000000000000000;
    storage[9] = 64'h0000000000000000;
    storage[10] = 64'h0000000000000000;
    storage[11] = 64'h0000000000000000;
    storage[12] = 64'h0000000000000000;
    storage[13] = 64'h0000000000000000;
    storage[14] = 64'h0000000000000000;
    storage[15] = 64'h0000000000000000;
    storage[16] = 64'h0000000000000000;
    storage[17] = 64'h0000000000000000;
    storage[18] = 64'h0000000000000000;
    storage[19] = 64'h0000000000000000;
    storage[20] = 64'h0000000000000000;
    storage[21] = 64'h0000000000000000;
    storage[22] = 64'h0000000000000000;
    storage[23] = 64'h0000000000000000;
    storage[24] = 64'h0000000000000000;
    storage[25] = 64'h0000000000000000;
    storage[26] = 64'h0000000000000000;
    storage[27] = 64'h0000000000000000;
    storage[28] = 64'h0000000000000000;
    storage[29] = 64'h0000000000000000;
    storage[30] = 64'h0000000000000000;
    storage[31] = 64'h0000000000000000;
    storage[32] = 64'h0000000000000000;
    storage[33] = 64'h0000000000000000;
    storage[34] = 64'h0000000000000000;
    storage[35] = 64'h0000000000000000;
    storage[36] = 64'h0000000000000000;
    storage[37] = 64'h0000000000000000;
    storage[38] = 64'h0000000000000000;
    storage[39] = 64'h0000000000000000;
    storage[40] = 64'h0000000000000000;
    storage[41] = 64'h0000000000000000;
    storage[42] = 64'h0000000000000000;
    storage[43] = 64'h0000000000000000;
    storage[44] = 64'h0000000000000000;
    storage[45] = 64'h0000000000000000;
    storage[46] = 64'h0000000000000000;
    storage[47] = 64'h0000000000000000;
    storage[48] = 64'h0000000000000000;
    storage[49] = 64'h0000000000000000;
    storage[50] = 64'h0000000000000000;
    storage[51] = 64'h0000000000000000;
    storage[52] = 64'h0000000000000000;
    storage[53] = 64'h0000000000000000;
    storage[54] = 64'h0000000000000000;
    storage[55] = 64'h0000000000000000;
    storage[56] = 64'h0000000000000000;
    storage[57] = 64'h0000000000000000;
    storage[58] = 64'h0000000000000000;
    storage[59] = 64'h0000000000000000;
    storage[60] = 64'h0000000000000000;
    storage[61] = 64'h0000000000000000;
    storage[62] = 64'h0000000000000000;
  end
  always @(posedge clk) begin
    if (w_port__en)
      storage[w_port__addr] <= w_port__data;
  end
  reg [63:0] _0_;
  always @(posedge clk) begin
    if (r_port__en) begin
      _0_ <= storage[r_port__addr];
    end
  end
  assign r_data = _0_;
  assign w_rdy = inner_level != 6'h3f;
  assign inner_r_rdy = | inner_level;
  assign w_port__en = w_rdy & w_en;
  assign \$1  = ~ r_rdy;
  assign \$2  = \$1  | r_en;
  assign r_port__en = inner_r_rdy & \$2 ;
  assign w_level = inner_level + r_rdy;
  assign \$3  = w_rdy & w_en;
  assign \$4  = w_port__addr == 6'h3e;
  assign \$5  = w_port__addr + 1'h1;
  assign \$6  = \$4  ? 7'h00 : \$5 ;
  assign \$7  = ~ r_rdy;
  assign \$8  = \$7  | r_en;
  assign \$9  = inner_r_rdy & \$8 ;
  assign \$10  = r_port__addr == 6'h3e;
  assign \$11  = r_port__addr + 1'h1;
  assign \$12  = \$10  ? 7'h00 : \$11 ;
  assign \$13  = w_rdy & w_en;
  assign \$14  = ~ r_rdy;
  assign \$15  = \$14  | r_en;
  assign \$16  = inner_r_rdy & \$15 ;
  assign \$17  = ~ \$16 ;
  assign \$18  = \$13  & \$17 ;
  assign \$19  = inner_level + 1'h1;
  assign \$20  = ~ r_rdy;
  assign \$21  = \$20  | r_en;
  assign \$22  = inner_r_rdy & \$21 ;
  assign \$23  = w_rdy & w_en;
  assign \$24  = ~ \$23 ;
  assign \$25  = \$22  & \$24 ;
  assign \$26  = inner_level - 1'h1;
  assign \$27  = ~ r_rdy;
  assign \$28  = \$27  | r_en;
  assign \$29  = inner_r_rdy & \$28 ;
  always @(posedge clk)
    w_port__addr <= \$30 ;
  always @(posedge clk)
    r_port__addr <= \$31 ;
  always @(posedge clk)
    inner_level <= \$32 ;
  always @(posedge clk)
    r_rdy <= \$33 ;
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$3 ) begin end
    \$30  = w_port__addr;
    if (\$3 ) begin
      \$30  = \$6 [5:0];
    end
    if (rst) begin
      \$30  = 6'h00;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$3 ) begin end
    \$31  = r_port__addr;
    if (\$9 ) begin
      \$31  = \$12 [5:0];
    end
    if (rst) begin
      \$31  = 6'h00;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$3 ) begin end
    \$32  = inner_level;
    if (\$18 ) begin
      \$32  = \$19 [5:0];
    end
    if (\$25 ) begin
      \$32  = \$26 [5:0];
    end
    if (rst) begin
      \$32  = 6'h00;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$3 ) begin end
    \$33  = r_rdy;
    if (\$29 ) begin
      \$33  = 1'h1;
    end else if (r_en) begin
      \$33  = 1'h0;
    end
    if (rst) begin
      \$33  = 1'h0;
    end
  end
  assign level = w_level;
  assign r_level = w_level;
  assign produce = w_port__addr;
  assign w_data = w_port__data;
  assign consume = r_port__addr;
  assign r_port__data = r_data;
endmodule

(* generator = "Amaranth" *)
module \t2router.wfifo (rst, r_en, w_rdy, r_data, w_port__data, w_en, r_rdy, clk);
  reg \$auto$verilog_backend.cc:2355:dump_module$4  = 0;
  wire \$1 ;
  wire \$10 ;
  wire [4:0] \$11 ;
  wire [4:0] \$12 ;
  wire \$13 ;
  wire \$14 ;
  wire \$15 ;
  wire \$16 ;
  wire \$17 ;
  wire \$18 ;
  wire [4:0] \$19 ;
  wire \$2 ;
  wire \$20 ;
  wire \$21 ;
  wire \$22 ;
  wire \$23 ;
  wire \$24 ;
  wire \$25 ;
  wire [4:0] \$26 ;
  wire \$27 ;
  wire \$28 ;
  wire \$29 ;
  wire \$3 ;
  reg [3:0] \$30 ;
  reg [3:0] \$31 ;
  reg [3:0] \$32 ;
  reg \$33 ;
  wire \$4 ;
  wire [4:0] \$5 ;
  wire [4:0] \$6 ;
  wire \$7 ;
  wire \$8 ;
  wire \$9 ;
  input clk;
  wire clk;
  (* init = 4'h0 *)
  wire [3:0] consume;
  reg [3:0] inner_level = 4'h0;
  wire inner_r_rdy;
  wire [4:0] level;
  (* init = 4'h0 *)
  wire [3:0] produce;
  output [47:0] r_data;
  wire [47:0] r_data;
  input r_en;
  wire r_en;
  wire [4:0] r_level;
  reg [3:0] r_port__addr = 4'h0;
  wire [47:0] r_port__data;
  wire r_port__en;
  output r_rdy;
  reg r_rdy = 1'h0;
  input rst;
  wire rst;
  wire [47:0] w_data;
  input w_en;
  wire w_en;
  wire [4:0] w_level;
  reg [3:0] w_port__addr = 4'h0;
  input [47:0] w_port__data;
  wire [47:0] w_port__data;
  wire w_port__en;
  output w_rdy;
  wire w_rdy;
  reg [47:0] storage [14:0];
  initial begin
    storage[0] = 48'h000000000000;
    storage[1] = 48'h000000000000;
    storage[2] = 48'h000000000000;
    storage[3] = 48'h000000000000;
    storage[4] = 48'h000000000000;
    storage[5] = 48'h000000000000;
    storage[6] = 48'h000000000000;
    storage[7] = 48'h000000000000;
    storage[8] = 48'h000000000000;
    storage[9] = 48'h000000000000;
    storage[10] = 48'h000000000000;
    storage[11] = 48'h000000000000;
    storage[12] = 48'h000000000000;
    storage[13] = 48'h000000000000;
    storage[14] = 48'h000000000000;
  end
  always @(posedge clk) begin
    if (w_port__en)
      storage[w_port__addr] <= w_port__data;
  end
  reg [47:0] _0_;
  always @(posedge clk) begin
    if (r_port__en) begin
      _0_ <= storage[r_port__addr];
    end
  end
  assign r_data = _0_;
  assign w_rdy = inner_level != 4'hf;
  assign inner_r_rdy = | inner_level;
  assign w_port__en = w_rdy & w_en;
  assign \$1  = ~ r_rdy;
  assign \$2  = \$1  | r_en;
  assign r_port__en = inner_r_rdy & \$2 ;
  assign w_level = inner_level + r_rdy;
  assign \$3  = w_rdy & w_en;
  assign \$4  = w_port__addr == 4'he;
  assign \$5  = w_port__addr + 1'h1;
  assign \$6  = \$4  ? 5'h00 : \$5 ;
  assign \$7  = ~ r_rdy;
  assign \$8  = \$7  | r_en;
  assign \$9  = inner_r_rdy & \$8 ;
  assign \$10  = r_port__addr == 4'he;
  assign \$11  = r_port__addr + 1'h1;
  assign \$12  = \$10  ? 5'h00 : \$11 ;
  assign \$13  = w_rdy & w_en;
  assign \$14  = ~ r_rdy;
  assign \$15  = \$14  | r_en;
  assign \$16  = inner_r_rdy & \$15 ;
  assign \$17  = ~ \$16 ;
  assign \$18  = \$13  & \$17 ;
  assign \$19  = inner_level + 1'h1;
  assign \$20  = ~ r_rdy;
  assign \$21  = \$20  | r_en;
  assign \$22  = inner_r_rdy & \$21 ;
  assign \$23  = w_rdy & w_en;
  assign \$24  = ~ \$23 ;
  assign \$25  = \$22  & \$24 ;
  assign \$26  = inner_level - 1'h1;
  assign \$27  = ~ r_rdy;
  assign \$28  = \$27  | r_en;
  assign \$29  = inner_r_rdy & \$28 ;
  always @(posedge clk)
    w_port__addr <= \$30 ;
  always @(posedge clk)
    r_port__addr <= \$31 ;
  always @(posedge clk)
    inner_level <= \$32 ;
  always @(posedge clk)
    r_rdy <= \$33 ;
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$4 ) begin end
    \$30  = w_port__addr;
    if (\$3 ) begin
      \$30  = \$6 [3:0];
    end
    if (rst) begin
      \$30  = 4'h0;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$4 ) begin end
    \$31  = r_port__addr;
    if (\$9 ) begin
      \$31  = \$12 [3:0];
    end
    if (rst) begin
      \$31  = 4'h0;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$4 ) begin end
    \$32  = inner_level;
    if (\$18 ) begin
      \$32  = \$19 [3:0];
    end
    if (\$25 ) begin
      \$32  = \$26 [3:0];
    end
    if (rst) begin
      \$32  = 4'h0;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$4 ) begin end
    \$33  = r_rdy;
    if (\$29 ) begin
      \$33  = 1'h1;
    end else if (r_en) begin
      \$33  = 1'h0;
    end
    if (rst) begin
      \$33  = 1'h0;
    end
  end
  assign level = w_level;
  assign r_level = w_level;
  assign produce = w_port__addr;
  assign w_data = w_port__data;
  assign consume = r_port__addr;
  assign r_port__data = r_data;
endmodule
